name: $(Date:yyyyMMdd).$(Rev:r)-$(Build.SourceBranchName)
trigger:
  branches:
    include:
      - master
      - release/*
  paths:
    include:
      - SSRSReports
    exclude:
      - Enterprise    

pool:
  name: UTY-BLD-POOL

variables:
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'Release'
  ArtifactoryDeployablesPath: 'rp-deployables-local/uty/UnifiedLogin/Master/$(Build.BuildNumber)'

jobs:

  - template: .azure-pipelines/rpt-job.yml
  