trigger:
- none

pool:
  #name: iee-bld-pool
  name: ie-provision-pool

parameters: 
- name: sandboxname
  displayName: sandboxname
  default: eng-static-upfmdacpac
# - name : BuildId
#   displayName: BuildId
- name: BuildNumber
  displayName: BuildNumber
  default: 1004368

variables:
  - name: sandboxip
    value: $(jgm)
  - name: sandboxname
    value: ${{ parameters.sandboxname }}-upfm-activity.sb.realpage.com
  - name: inv
    value: SSRSReports/.azure-pipelines/Ansible/inv
  - name : IE_inv
    value: SSRSReports/.azure-pipelines/Ansible/IE_inventory.ini
  - name: ArtifactsDirectory
    value: $(System.ArtifactsDirectory)
  # - name: BuildId
  #   value: ${{ parameters.BuildId }}
  - name: dacpac-playbook
    value: SSRSReports/.azure-pipelines/Ansible/deploy-dacpac.yaml
  - name: BuildNumber
    value: ${{ parameters.BuildNumber }}

stages:
  - stage: "Deploy"
    jobs:
      - job: "fetchip"
        steps:        
          - task: Bash@3
            displayName: Fetch GatewayIP
            inputs:  
              targetType: 'inline'
              script: |
                source /opt/ansible/2.9/bin/activate
                jumpbox=$(ansible rcddvowwngx101 -m shell -a "cat /etc/nginx/conf.d/* | grep -A 4 "$(sandboxname)" | tail -1 | grep -oE '[0-9.]+' | awk -F '/' '{print $3}'" -b -i $(IE_inv) | tail -1)
                if [ -z "$jumpbox" ]; then
                echo "##vso[task.logissue type=error]Could not fetch the GatewayIP. Check nginx server hostname and DNS name exists"
                echo "##vso[task.complete result=Failed;]"
                fi
                echo "jumpbox:$jumpbox"
                echo "##vso[task.setvariable variable=jgm]$jumpbox"

          - task: CmdLine@2
            displayName: Display GatewayIP
            inputs:   
              script: |
                echo 'Printing $(jgm)'
                echo 'Printing $(sandboxip)'

          - task:  CmdLine@2
            displayName: PingTest
            inputs:
               script: |
                 source /opt/ansible/2.9/bin/activate
                 ansible -m win_ping win -i $(inv) -e "sandboxip=$(sandboxip)"
          - task: ArtifactoryToolsInstaller@1
            inputs:
              artifactoryService: 'Artifactory'
              cliInstallationRepo: 'jfrog-cli-virtual'
          - task: ArtifactoryGenericDownload@3
            inputs:
              connection: 'Artifactory'
              specSource: 'taskConfiguration'
              fileSpec: |
                {
                  "files": [
                    {
                      "pattern": "rp-deployables-local/uty/UnifiedLogin/ULDB/$(BuildNumber).zip",
                      "target": "$(System.ArtifactsDirectory)/",
                      "explode": "true",
                      "flat": "true"
                    }
                  ]
                }
              failNoOp: true
          - task: CmdLine@2
            inputs:
              script: | 
                ls -la $(System.ArtifactsDirectory)/DB_Identity
                
          - task: CmdLine@2
            inputs:
              script: |
                source /opt/ie-build/ansible2.9/bin/activate
                ansible-playbook -vvv $(dacpac-playbook) -i $(inv) -e "sandboxip=$(sandboxip)" --extra-vars "ArtifactsDirectory=$(ArtifactsDirectory)"
            