// Templates

{{{ include("templates/templates.inc.js") }}}

// Config

{{{ include("config/ilm-leadanalytics.js") }}}

// Controllers

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/property-groups.js") }}}

// Models

{{{ include("models/properties-config.js") }}}
{{{ include("models/property-groups-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/ilm-leadanalytics.js") }}}
{{{ include("models/sync-manager.js") }}}
