---
- name: Copy Files from Linux to Windows
  hosts: win
  gather_facts: false
  tasks:
    - name: Copy files artifact zip file
      win_copy:
        src: '{{ ArtifactsDirectory }}/dacpac/'
        dest: D:\Identity\prod\DB_Deploy
    - name: Copy files artifact zip file
      win_copy:
        src: '{{ ArtifactsDirectory }}/dacpac/'
        dest: D:\Identity\prod\Scripts
    - name: Execute the powershell script
      win_shell: D:\Identity\prod\Scripts\SQL_DatabaseBackup_PS1.ps1