apiVersion: v1
kind: ConfigMap
metadata:
  name: unifiedloginlanding-api-config-$(environmentName)
  # namespace: unified-login
  labels:
    product: une
    module: unifiedloginlandingapi
    location: rke2
    environment: $(environmentName)
data:
  ASPNETCORE_ENVIRONMENT: $(environmentName)
  TraceIdRatioBasedSampler: "$(TraceIdRatioBasedSampler)"
  Serilog__MinimumLevel__Default: "$(SerilogMinimumLevelDefault)"
