apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-login-coreapienterprisev2-config-$(environmentName)
  # namespace: unified-login
  labels:
    product: une
    module: unified-login-coreapienterprisev2
    location: rke2
    environment: $(environmentName)
data:
  ASPNETCORE_ENVIRONMENT: $(environmentName)
  TraceIdRatioBasedSampler: "$(TraceIdRatioBasedSampler)"
  Serilog__MinimumLevel__Default: "$(SerilogMinimumLevelDefault)"
  OTEL_RESOURCE_ATTRIBUTES: "$(OTEL_RESOURCE_ATTRIBUTES)"

