// Templates
{{{ include("templates/templates.inc.js") }}}

// Controllers
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/property-groups.js") }}}
{{{ include("controllers/property-group-aside.js") }}}
{{{ include("controllers/property-group-icon.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/roles-radio.js") }}}

// Models
{{{ include("models/marketing-center.js") }}}
{{{ include("models/properties-config.js") }}}
{{{ include("models/property-group-aside-config.js") }}}
{{{ include("models/property-group-config.js") }}}
{{{ include("models/property-group-details-aside.js") }}}
{{{ include("models/property-group-details.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}

// Services 
{{{ include("services/property-group-data.js") }}}
{{{ include("services/property-group-aside-data.js") }}}
{{{ include("services/properties-data.js") }}}
{{{ include("services/roles-data.js") }}}