trigger: none
schedules:
 - cron: "0 9 * * 2"
   displayName: Weekly at 9AM UTC / 3AM CST on Tuesdays (day 2 of week)   
   branches:
     include:
     - master
     - feature/2027718_fortify_fixes
   always: true

resources:
  repositories:   
  - repository: UnifiedLoginMain
    type: git
    name: unified-login-main
    ref: master

pool:
  name: Fortify-BLD-POOL

variables:
  ReleaseId: 745546
  ArchiveFileName: '$(build.buildId).zip'
  ArchiveLocation: '$(build.artifactStagingDirectory)/zipped/'
  pipeline.releaseId: '$(ReleaseId)'
  SourceLocation: '$(Agent.BuildDirectory)\s'

steps:
- checkout: UnifiedLoginMain
- task: ArchiveFiles@2
  displayName: 'Archive $(SourceLocation)'
  inputs:
    rootFolderOrFile: '$(SourceLocation)'
    archiveFile: '$(ArchiveLocation)$(ArchiveFileName)'

- task: FortifyOnDemandStatic@8
  displayName: 'Run Fortify on Demand static assessment'
  inputs:
    FortifyProjects: '$(ArchiveLocation)'
    ReleaseId: $(ReleaseId)
    FodConnection: 'fortify-on-demand'
    EntitlementPreference: 1
    InProgressScanActionType: 2
    RemediationScanPreference: 2
    PolicyFailAction: 0
    ReleaseOptions: '0'
    EntitlementSelection: '1'
    OverrideScanSettings: '2'