{{{ include("templates/templates.inc.js") }}}

{{{ include("config/tabs.js") }}}

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/roles.js") }}}


{{{ include("filters/renters-insurance-translator.js") }}}

{{{ include("models/properties-grid.js") }}}
{{{ include("models/renters-insurance.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/tabs.js") }}}

{{{ include("services/properties.js") }}}
{{{ include("services/roles.js") }}}
