// Config


// Controllers

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties-radio.js") }}}
{{{ include("controllers/properties.js") }}}

// Models

{{{ include("models/prospect-contact-center.js") }}}
{{{ include("models/properties-config.js") }}}
{{{ include("models/tabs-menu.js") }}}

// Services

{{{ include("services/properties-data.js") }}}

// Templates

{{{ include("templates/templates.inc.js") }}}
