{{{ include("controllers/start-profile.js") }}}

{{{ include("filters/start-profile-translator.js") }}}

{{{ include("models/start-profile.js") }}}
{{{ include("models/start-profile-data.js") }}}
{{{ include("models/start-profile-config.js") }}}
{{{ include("models/profile-options.js") }}}

{{{ include("services/get-user.js") }}}
{{{ include("services/get-profile.js") }}}


{{{ include("services/start-profile.js") }}}
{{{ include("services/industry-job-title.js") }}}
{{{ include("services/phone-type.js") }}}
