//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RP.Enterprise.Subsystem.ProductLauncher.Web.Landing {
    
    
    public partial class ServiceCheck {
    }
}
