--Set all PersistRight flag to 0 and set 1 for only below rights
GO
UPDATE [Security].[Right] SET PersistRight = 0 WHERE PersistRight=1

UPDATE [Security].[Right] SET PersistRight = 1 WHERE RightName IN 
('activatedeactivateusers'
,'CloneUser'
,'CreateUser'
,'EditOtherProfile'
,'EditUsers'
,'AbilityToImportUsers'
,'LockUnlockUsers'
,'MigrationTool'
,'ViewUsers'
,'ManageAdminSupportPortalProductAccess'
,'ManageAssetOptimizationProductAccess'
,'ManageClickPayProductAccess'
,'ManageClientPortalProductAccess'
,'ManageCommunityRewardsProductAccess'
,'ManageContactCenterMaintenanceProductAccess'
,'ManageDataHubProductaccess'
,'ManageDepositAlternativeProductAccess'
,'ManageDocumentManagementProductAccess'
,'ManageAccountingProductAccess'
,'G5LLMarketingProductsProductaccess'
,'ManageG5/LLMarketingProductsProductaccess'
,'ManageHandsOnTrainingSystemProductAccess'
,'ManageILMLeadManagemementProductAccess'
,'AccessIntegrationMarketplace'
,'ManageKnockProductaccess'
,'ManageLead2LeaseProductAccess'
,'ManageMarketingCenterProductAccess'
,'ManageHomeSharingProductAccess'
,'ManageOneSiteProductAccess'
,'ManageOnSiteProductAccess'
,'CIMPLManagePII'
,'ManagePortfolioManagementProductAccess'
,'ProspectContactCenterProductAccess'
,'ManageRelate247ProductAccess'
,'ManageRenovationManager'
,'ManageRentersInsuranceProductAccess'
,'AddEditResidentPortalUser'
,'ManageSGTourProductAccess'
,'CIMPLManageSensitiveFinancialData'
,'ManageIntelligentBuildingTrashProductAccess'
,'ManageIntelligentBuildingWaterProductAccess'
,'ManageSpendManagementProductAccess'
,'ManageUnifiedAmenitiesProductAccess'
,'ManageUtilityManagementProductAccess'
,'ManageVendorComplianceProductAccess'
,'ManageVendorMarketplaceProductAccess'
)

GO