GO
IF NOT EXISTS (select * from [Maintenance].[PURGECONFIGPARAMS] where PROGRAMNAME = 'PUR_Activity' and PURGEID = 1) 
begin
  Print 'Insert PURGECONFIGPARAMS where PROGRAMNAME = "PUR_ActivityAttempts" and PURGEID = 1'
  Insert into [Maintenance].[PURGECONFIGPARAMS](PROGRAMNAME,PURGEID,SCHEMANAME,TABLENAME,COLUMNNAME,HST_TABLENAME,RETENTIONDAYS,COMMITPOINT,PURGEFLAG,BACKUPFLAG)
    select 'PUR_Activity',1,'ident','ActivityAttempts','LastAttemptDateTime',NULL,730,50000,'Y','N';
end
  
if not exists (select * from [Maintenance].[PURGECONFIGPARAMS] where PROGRAMNAME = 'PUR_LOGS' and PURGEID = 2) 
begin
  Print 'Insert PURGECONFIGPARAMS where PROGRAMNAME = "PUR_LOGS" and PURGEID = 2'
  Insert into [Maintenance].[PURGECONFIGPARAMS](PROGRAMNAME,PURGEID,SCHEMANAME,TABLENAME,COLUMNNAME,HST_TABLENAME,RETENTIONDAYS,COMMITPOINT,PURGEFLAG,BACKUPFLAG)
    select 'PUR_LOGS',2,'DBO','DatabaseLog','PostTime',NULL,14,50000,'Y','N';
end
  
if not exists (select * from [Maintenance].[PURGECONFIGPARAMS] where PROGRAMNAME = 'PUR_BATCH' and PURGEID =3) 
begin
  Print 'Insert PURGECONFIGPARAMS where PROGRAMNAME = "PUR_BATCH" and PURGEID = 3'
  Insert into [Maintenance].[PURGECONFIGPARAMS](PROGRAMNAME,PURGEID,SCHEMANAME,TABLENAME,COLUMNNAME,HST_TABLENAME,RETENTIONDAYS,COMMITPOINT,PURGEFLAG,BACKUPFLAG)
    select 'PUR_BATCH',3,'Batch','BatchProcessorError','CreatedDateTime',NULL,1094,50000,'Y','N';
end
  
if not exists (select * from [Maintenance].[PURGECONFIGPARAMS] where PROGRAMNAME = 'PUR_BATCH' and PURGEID = 4) 
begin
  Print 'Insert PURGECONFIGPARAMS where PROGRAMNAME = "PUR_BATCH" and PURGEID = 4'
  Insert into [Maintenance].[PURGECONFIGPARAMS](PROGRAMNAME,PURGEID,SCHEMANAME,TABLENAME,COLUMNNAME,HST_TABLENAME,RETENTIONDAYS,COMMITPOINT,PURGEFLAG,BACKUPFLAG)
    select 'PUR_BATCH',4,'Batch','BatchProcessorLog','CreatedDateTime',NULL,1095,50000,'Y','N';
END
if not exists (select * from [Maintenance].[PURGECONFIGPARAMS] where PROGRAMNAME = 'PUR_BATCH' and PURGEID = 5) 
begin
  Print 'Insert PURGECONFIGPARAMS where PROGRAMNAME = "PUR_BATCH" and PURGEID = 5'
  Insert into [Maintenance].[PURGECONFIGPARAMS](PROGRAMNAME,PURGEID,SCHEMANAME,TABLENAME,COLUMNNAME,HST_TABLENAME,RETENTIONDAYS,COMMITPOINT,PURGEFLAG,BACKUPFLAG)
    select 'PUR_BATCH',5,'Batch','BatchProcessor','CreatedDateTime',NULL,1095,50000,'Y','N';
END
GO