{{{ include("templates/templates.inc.js") }}}

{{{ include("config/product-panel.js") }}}
{{{ include("controllers/product-controller.js") }}}
{{{ include("controllers/product-properties.js") }}}
{{{ include("controllers/product-roles.js") }}}
{{{ include("controllers/product-roles-radio.js") }}}
{{{ include("controllers/product-properties-radio.js") }}}

{{{ include("models/product-panel.js") }}}
{{{ include("models/config-data-model.js") }}}
{{{ include("models/grid-factory.js") }}}
{{{ include("models/config-model.js") }}}
{{{ include("models/product-panel-tabs-data-factory.js") }}}
{{{ include("models/data-json.js") }}}
{{{ include("models/data-json-pcc.js") }}}
{{{ include("models/data-json-mc.js") }}}
{{{ include("models/data-json-os.js") }}}

{{{ include("services/roles-data.js") }}}
{{{ include("services/properties-data.js") }}}
