CREATE TABLE [Ident].[SettingCategoryType]
(
	[SettingCategoryTypeId] SMALLINT NOT NULL IDENTITY, 
    [Name] NVARCHAR(100) NOT NULL,
CONSTRAINT [PK_SettingCategoryType] PRIMARY KEY CLUSTERED 
(
	[SettingCategoryTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
