
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/onesite-delete-modal.js") }}}
{{{ include("controllers/onesite-roles.js") }}}
{{{ include("controllers/onesite-status-message.js") }}}


{{{ include("models/onesite-assign-rights-products-data.js") }}}
{{{ include("models/onesite-message-modal.js") }}}
{{{ include("models/onesite-message.js") }}}
{{{ include("models/onesite-roles-actions.js") }}}
{{{ include("models/onesite-roles-config.js") }}}
{{{ include("models/onesite-roles.js") }}}

{{{ include("directives/onesite-actions.js") }}}

{{{ include("services/onesite-assign-rights-products.js") }}}
{{{ include("services/onesite-clone-role.js") }}}
{{{ include("services/onesite-delete-role.js") }}}
{{{ include("services/onesite-roles.js") }}}



