CREATE TABLE [Enterprise].[ActionValueType](
	[ActionValueTypeID] [tinyint] IDENTITY(1,1) NOT NULL,
	[Value] NVARCHAR(50) NULL,
	[Description] NVARCHAR(200) NULL,
 CONSTRAINT [PK_ActionValyeTypeID] PRIMARY KEY CLUSTERED 
(
	[ActionValueTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO