CREATE TABLE [Enterprise].[Action](
	[ActionID] [int] NOT NULL IDENTITY(1,1),
	[ParentActionId] [int] NULL,
	[ProductId] [int] NULL,
	[ObjectValue] NVARCHAR(500) NULL,
	[ObjectType] NVARCHAR(200) NULL,
	[ActionvalueTypeId] [tinyint] NULL,
	[Description] NVARCHAR(200) NULL,
 [LastUpdateDateTime] DATETIME NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT [FK_Action_Action] FOREIGN KEY([ParentActionId]) REFERENCES [Enterprise].[Action] ([ActionID]),
 CONSTRAINT [FK_Action_ActionSetting] FOREIGN KEY([ActionvalueTypeId]) REFERENCES [Enterprise].[ActionValueType] ([ActionValueTypeID]) ON UPDATE CASCADE ON DELETE CASCADE, 
 CONSTRAINT [FK_Action_Product] FOREIGN KEY([ProductId]) REFERENCES [Enterprise].[Product] ([ProductId]) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT [PK_Action] PRIMARY KEY CLUSTERED 
(
	[ActionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Action] ON [Enterprise].[Action]
(
	[ActionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
GO
CREATE NONCLUSTERED INDEX [IX_Action_ObjectValue] ON [Enterprise].[Action]
(
	[ObjectValue] ASC
)
INCLUDE ( ProductId, [ObjectType], ActionValueTypeId) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
GO
CREATE NONCLUSTERED INDEX [IX_Action_ParentActionId] ON [Enterprise].[Action]
(
	[ParentActionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO