CREATE TABLE [Enterprise].[Party]
(
	[PartyId]		BIGINT					IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL, 
    [RealPageId]	UNIQUEIDENTIFIER	CONSTRAINT [DF_Party_rowguid] DEFAULT (NEWSEQUENTIALID()) ROWGUIDCOL NOT NULL, 
	[CreateDate]	DATETIME			CONSTRAINT [DF_Party_CreateDate] DEFAULT (GETUTCDATE()) NOT NULL,
    CONSTRAINT [PK_Party] PRIMARY KEY CLUSTERED ([PartyId] ASC)
)
GO

CREATE UNIQUE NONCLUSTERED INDEX [AK_Party_rowguid]
	ON [Enterprise].[Party]([RealPageId] ASC);
GO
CREATE INDEX IDX_Party_Comp01 ON Enterprise.Party
(PartyId, RealPageId);