CREATE TABLE [Enterprise].[RightValueType]
(
	[RightValueTypeId] INT IDENTITY (1,1) NOT NULL, 
    [Value] NVARCHAR(200) NOT NULL DEFAULT -1, 
    [ShortName] NVARCHAR(50) NULL,
     [StatusTypeId] INT NULL ,
    [Description] NVARCHAR(200) NULL,   
[LastUpdateDateTime] DATETIME NULL DEFAULT GETUTCDATE(), 
    [VisibilityStatusId] INT NULL, 
    [ProductId] INT NULL, 
    [TargetProductId] INT NULL, 
    CONSTRAINT PK_RightValueType PRIMARY KEY CLUSTERED (RightValueTypeId) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT FK_RightValueType_StatusType FOREIGN KEY (StatusTypeId) REFERENCES Enterprise.StatusType(StatusTypeId) ON UPDATE  NO ACTION  ON DELETE  NO ACTION 
)
GO
CREATE NONCLUSTERED INDEX [IX_RightValueType_Value] ON [Enterprise].[RightValueType]
(
	[Value] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
