CREATE TABLE [Enterprise].[Role](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[ParentRoleID] [int] NULL,
	[RoleTypeID] [int] NOT NULL DEFAULT -1,
	[PartyID] BIGINT NOT NULL DEFAULT -1,
 [RoleValueTypeId] INT NOT NULL DEFAULT -1, 
 DefaultRole BIT NOT NULL DEFAULT 0,
    [LastUpdateDateTime] DATETIME NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT FK_Role_Party FOREIGN KEY (PartyID) REFERENCES Enterprise.Party	(PartyId) ON UPDATE CASCADE ,
 CONSTRAINT [FK_Role_RoleType] FOREIGN KEY([RoleTypeID]) REFERENCES [Enterprise].[RoleType] ([PartyRoleTypeId]) ON UPDATE CASCADE,
 CONSTRAINT [FK_Role_Role] FOREIGN KEY([ParentRoleID]) REFERENCES [Enterprise].[Role] ([RoleID]),
 CONSTRAINT [FK_Role_RoleValueType] FOREIGN KEY ([RoleValueTypeId]) REFERENCES [Enterprise].[RoleValueType] (RoleValueTypeId), 
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_Role] ON [Enterprise].[Role]
(
	[RoleID] ASC,
	[PartyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_Role_RoleValueTypeId] ON [Enterprise].[Role]
(
	[RoleValueTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO