CREATE TABLE [Enterprise].[UserActions](
	[UserActionID] [int] IDENTITY(1,1) NOT NULL,
	[ActionID] [int] NULL,
	[RightID] [int] NULL,
	[Status] [INT] NULL,
 [LastUpdateDateTime] DATETIME NULL DEFAULT GETUTCDATE(), 
    CONSTRAINT [FK_UserActions_Action] FOREIGN KEY([ActionID]) REFERENCES [Enterprise].[Action] ([ActionID]) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT [FK_UserActions_Right] FOREIGN KEY([RightID]) REFERENCES [Enterprise].[Right] ([RightID]) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT [FK_UserActions_StatusType] FOREIGN KEY([Status]) REFERENCES [Enterprise].[StatusType] ([StatusTypeId]) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT [PK_UserActions] PRIMARY KEY CLUSTERED 
(
	[UserActionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_UserActions_ActionId] ON [Enterprise].[UserActions]
(
	[ActionID] ASC,
	[RightID] ASC
)
INCLUDE ( 	[Status]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_UserActions_RightId] ON [Enterprise].[UserActions]
(
	[RightID] ASC,
	[ActionID] ASC
)
INCLUDE ( 	[Status]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO