{{{ include("templates/templates.inc.js") }}}

{{{ include("config/res-app.js") }}}
{{{ include("config/goals-config.js") }}}


{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/goals.js") }}}
{{{ include("controllers/res-app-product-access.js") }}}


{{{ include("models/roles-config.js") }}}
{{{ include("models/res-app-tabs-menu.js") }}}
{{{ include("models/res-app-roles.js") }}}



{{{ include("services/roles-data.js") }}}
{{{ include("services/res-app-tabs-data.js") }}}
