{{{ include("templates/templates.inc.js") }}}

{{{ include("config/user-mgmt.js") }}}

{{{ include("controllers/rights-list-aside.js") }}}
{{{ include("controllers/role-info-icon.js") }}}
{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/user-mgmt-product-access.js") }}}
{{{ include("controllers/user-mgmt-properties-roles.js") }}}

{{{ include("models/rights-list-aside.js") }}}
{{{ include("models/rights-list-grid.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/side-menu-config.js") }}}
{{{ include("models/user-mgmt-production-tabs-menu.js") }}}
{{{ include("models/user-mgmt-rights.js") }}}
{{{ include("models/user-mgmt-roles.js") }}}



{{{ include("services/roles-data.js") }}}
{{{ include("services/user-mgmt-rights-aside.js") }}}
{{{ include("services/user-mgmt-tabs-data.js") }}}
