
{{{ include("templates/templates.inc.js") }}}

{{{ include("directives/user-mgmt-actions.js") }}}

{{{ include("controllers/user-mgmt-delete-modal.js") }}}
{{{ include("controllers/user-mgmt-roles.js") }}}
{{{ include("controllers/user-mgmt-status-message.js") }}}


{{{ include("models/user-mgmt-assign-rights-products-data.js") }}}
{{{ include("models/user-mgmt-message-modal.js") }}}
{{{ include("models/user-mgmt-message.js") }}}
{{{ include("models/user-mgmt-roles-actions.js") }}}
{{{ include("models/user-mgmt-roles-config.js") }}}
{{{ include("models/user-mgmt-roles.js") }}}


{{{ include("services/user-mgmt-clone-role.js") }}}
{{{ include("services/user-mgmt-delete-role.js") }}}
{{{ include("services/user-mgmt-default-role.js") }}}
{{{ include("services/user-mgmt-roles.js") }}}




