stages:
  - stage: dev
    displayName: DEV
    dependsOn: [build]
    pool: k8s-rel-pool
    variables:    
      - name: environmentName
        value: dev
      - name: Server.LandingApiHostName
        value: 'www-dev2.realpage.com/apiv2'
      - name: Server.EnterpriseApiHostName
        value: 'www-dev2.realpage.com/apienterprisev2'
      - name: K8s.ManifestFolder
        value: 'k8s/rancher'
      - name: K8s.Namespace
        value: 'une-dev'
      - name: K8s.LandingApiReplicas
        value: '2'
      - name: K8s.EnterpriseApiReplicas
        value: '2'
      - name: K8s.Registry
        value: 'artifacts.realpage.com/artifactory/docker-virtual/uty/public/unifiedloginmaincore'
      - name: K8s.LandingApiImage
        value: '$(K8s.Registry)/api'
      - name: K8s.LandingApiEnterpriseImage
        value: '$(K8s.Registry)/apienterprise'
      - group: 'unified-login-dev'
    jobs:
      - template: ../jobs/k8s-job.yml
        parameters:
          k8sServiceConnections: ['rp1-nonprod--unified-platform']
          environment: unified-login-dev

      # - template: ../jobs/dacpac-job.yml
      #   parameters:
      #     environment: unified-login-dev
      #     condition: and(succeeded(), eq(variables['isDatabaseDeployment'], true))
      #     dependsOn: [k8s]