stages:
  - stage: sat
    displayName: SAT
    dependsOn: [qa]
    pool: k8s-rel-pool
    variables:    
      - name: environmentName
        value: sat
      - name: Server.LandingApiHostName
        value: 'my2sat.realpage.com'
      - name: K8s.ManifestFolder
        value: 'k8s/rancher'
      - name: K8s.Namespace
        value: 'une-sat'
      - name: K8s.LandingApiReplicas
        value: '1'
      - name: K8s.EnterpriseApiReplicas
        value: '1'
      - name: K8s.BatchProcessorReplicas
        value: '0'
      - name: K8S_MIN_REPLICAS
        value: '1'
      - name: K8S_MAX_REPLICAS
        value: '10'
      - name: K8s.Registry
        value: 'artifacts.realpage.com/rp-docker-local/uty/public/unifiedloginmaincore'
      - name: K8s.LandingApiImage
        value: '$(K8s.Registry)/api'
      - name: K8s.LandingApiEnterpriseImage
        value: '$(K8s.Registry)/apienterprise'
      - name: K8s.BatchProcessorImage
        value: '$(K8s.Registry)/unifiedlogin.batchprocessor'
      - group: 'unified-login-sat'
    jobs:
      - template: ../jobs/k8s-job.yml
        parameters:
          k8sServiceConnections: ['rp1-nonprod--unified-platform']
          environment: unified-login-sat