stages:
  - stage: test_ready
    displayName: Ready for Testing
    dependsOn: [int]
    pool: k8s-rel-pool
    variables:
      - group: 'unified-login-ready'                  
    jobs:
      - job:
        displayName: 'Approval'
        steps:
        - bash: echo "Approved"          
          displayName: 'Approved'