// Config


// Controllers

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/entity-groups.js") }}}
{{{ include("controllers/entity-group-aside.js") }}}
{{{ include("controllers/entity-group-icon.js") }}}
{{{ include("controllers/entities.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/companies.js") }}}
{{{ //include("controllers/accounting-main.js") }}}


// Models

{{{ include("models/accounting.js") }}}
{{{ include("models/entities-config.js") }}}
{{{ include("models/entity-group-aside-config.js") }}}
{{{ include("models/entity-group-config.js") }}}
{{{ include("models/entity-group-details-aside.js") }}}
{{{ include("models/entity-group-details.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/companies-config.js") }}}
{{{ include("models/switch-model.js") }}}
{{{ include("models/tabs.js") }}}


// Services

{{{ include("services/entity-group-data.js") }}}
{{{ include("services/entity-group-aside-data.js") }}}
{{{ include("services/entities-data.js") }}}
{{{ include("services/roles-data.js") }}}
{{{ include("services/companies-data.js") }}}


// Templates

{{{ include("templates/templates.inc.js") }}}
