{{{ include("templates/templates.inc.js") }}}

{{{ include("config/axiometrics.js") }}}

{{{ include("services/axiometrics-tabs-data.js") }}}


{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/markets.js") }}}
{{{ include("controllers/companies.js") }}}
{{{ include("controllers/company-roles.js") }}}

{{{ include("models/axiometrics.js") }}}
{{{ include("models/markets-config.js") }}}
{{{ include("models/company-config.js") }}}
{{{ include("models/company-roles.js") }}}
{{{ include("models/axm-sync-manager.js") }}}
