// Config

{{{ include("config/aside.js") }}}

// Controllers

{{{ include("controllers/manage-profile.js") }}}

// Filters

{{{ include("filters/manage-profile.js") }}}

// Models

{{{ include("models/aside.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/user-profile.js") }}}

// Services

{{{ include("services/tabs-data.js") }}}
{{{ include("services/tabs-manager.js") }}}

// Templates

{{{ include("templates/templates.inc.js") }}}
