
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/acct-rights.js") }}}

{{{ include("models/acct-products-config.js") }}}
{{{ include("models/acct-products-menu.js") }}}
{{{ include("models/acct-rights-actions.js") }}}
{{{ include("models/acct-rights-config.js") }}}
{{{ include("models/acct-rights.js") }}}

{{{ include("directives/acct-actions.js") }}}

{{{ include("services/acct-products.js") }}}
{{{ include("services/acct-rights.js") }}}



