
{{{ include("config/tabs.js") }}}
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/property-groups.js") }}}
{{{ include("controllers/property-info-icon.js") }}}
{{{ include("controllers/property-list-aside.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("models/business-intelligence.js") }}}
{{{ include("models/properties-aside-config.js") }}}
{{{ include("models/properties-config.js") }}}
{{{ include("models/properties-list-aside.js") }}}
{{{ include("models/property-group-config.js") }}}
{{{ include("models/property-group-model.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("templates/templates.inc.js") }}}
