{{{ include("config/tabs.js") }}}
{{{ include("config/unified-amenities.js") }}}

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties-grid.js") }}}
{{{ include("controllers/rights-list-aside.js") }}}
{{{ include("controllers/role-info-icon.js") }}}
{{{ include("controllers/roles-grid.js") }}}
{{{ include("controllers/roles-radio.js") }}}

{{{ include("models/properties-grid.js") }}}
{{{ include("models/rights-list-aside.js") }}}
{{{ include("models/rights-list-grid.js") }}}
{{{ include("models/rights-model.js") }}}
{{{ include("models/role-model.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/tabs.js") }}}
{{{ include("models/unified-amenities.js") }}}

{{{ include("services/properties-data.js") }}}
{{{ include("services/rights-aside-data.js") }}}
{{{ include("services/roles-data.js") }}}

{{{ include("templates/templates.inc.js") }}}
