// Templates
{{{ include("templates/templates.inc.js") }}}

// Controllers
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/property-group.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/property-group-radio.js") }}}

// Models
{{{ include("models/property-group-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/spend-management.js") }}}

// Services 
{{{ include("services/property-group-data.js") }}}
{{{ include("services/roles-data.js") }}}