// Templates
{{{ include("templates/templates.inc.js") }}}

// Controllers
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/property-group-radio.js") }}}
{{{ include("controllers/notifications.js") }}}

// Models
{{{ include("models/properties-config.js") }}}
{{{ include("models/property-group-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/vendor-compliance.js") }}}

// Services 
{{{ include("services/properties-data.js") }}}
{{{ include("services/property-group-data.js") }}}
{{{ include("services/roles-data.js") }}}