
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-assign-role.js") }}}

{{{ include("models/spndmgmt-assign-role-config.js") }}}
{{{ include("models/spndmgmt-assign-role.js") }}}
{{{ include("models/spndmgmt-assign-tabs-menu.js") }}}

{{{ include("services/spndmgmt-assign-role-save.js") }}}
{{{ include("services/spndmgmt-assign-role-tabs-manager.js") }}}
{{{ include("services/spndmgmt-assign-role.aside.js") }}}
{{{ include("services/spndmgmt-assign-tabs-context.js") }}}
{{{ include("services/spndmgmt-assign-tabs-data.js") }}}
