// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.realpage.avro.unity.unified-login
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Schema for unified-login user activation or deactivation
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class UnifiedLoginUserStatus : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""UnifiedLoginUserStatus"",""doc"":""Schema for unified-login user activation or deactivation"",""namespace"":""com.realpage.avro.unity.unified-login"",""fields"":[{""name"":""user_login_name"",""doc"":""Username or login name of the user."",""default"":null,""type"":[""null"",""string""]},{""name"":""is_active"",""doc"":""Status of the user."",""default"":null,""type"":[""null"",""boolean""]},{""name"":""user_activation_deactivation_date"",""doc"":""User's last updated date i.e when user is deactivated or activated. Time zone is UTC."",""default"":null,""type"":[""null"",{""type"":""int"",""logicalType"":""date""}]}]}");
		/// <summary>
		/// Username or login name of the user.
		/// </summary>
		private string _user_login_name;
		/// <summary>
		/// Status of the user.
		/// </summary>
		private System.Nullable<System.Boolean> _is_active;
		/// <summary>
		/// User's last updated date i.e when user is deactivated or activated. Time zone is UTC.
		/// </summary>
		private System.Nullable<System.DateTime> _user_activation_deactivation_date;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return UnifiedLoginUserStatus._SCHEMA;
			}
		}
		/// <summary>
		/// Username or login name of the user.
		/// </summary>
		public string user_login_name
		{
			get
			{
				return this._user_login_name;
			}
			set
			{
				this._user_login_name = value;
			}
		}
		/// <summary>
		/// Status of the user.
		/// </summary>
		public System.Nullable<System.Boolean> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				this._is_active = value;
			}
		}
		/// <summary>
		/// User's last updated date i.e when user is deactivated or activated. Time zone is UTC.
		/// </summary>
		public System.Nullable<System.DateTime> user_activation_deactivation_date
		{
			get
			{
				return this._user_activation_deactivation_date;
			}
			set
			{
				this._user_activation_deactivation_date = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.user_login_name;
			case 1: return this.is_active;
			case 2: return this.user_activation_deactivation_date;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.user_login_name = (System.String)fieldValue; break;
			case 1: this.is_active = (System.Nullable<System.Boolean>)fieldValue; break;
			case 2: this.user_activation_deactivation_date = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
