{{{ include("config/portfolio-management.js") }}}
{{{ include("controllers/entities.js") }}}
{{{ include("controllers/entity-roles.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/product-access.js") }}}
{{{ include("models/roles-entities-config.js") }}}
{{{ include("models/entity-roles.js") }}}
{{{ include("models/pm-sync-manager.js") }}}
{{{ include("models/portfolio-management.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("services/tabs-menu.js") }}}
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/entities-info.js") }}}
{{{ include("models/entities-list-aside.js") }}}
{{{ include("controllers/entities-list-aside.js") }}}

{{{ include("models/entities-assign-model.js") }}}
{{{ include("services/assign-entities-context.js") }}}

{{{ include("models/entities-aside-grid-config.js") }}}