{{{ include("config/portfolio-management.js") }}}
{{{ include("controllers/entities.js") }}}
{{{ include("controllers/entity-roles.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/product-access.js") }}}
{{{ include("models/entities-config.js") }}}
{{{ include("models/entity-roles.js") }}}
{{{ include("models/pm-sync-manager.js") }}}
{{{ include("models/portfolio-management.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("services/tabs-menu.js") }}}
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/entities-list-aside.js") }}}
{{{ include("models/entities-list-grid.js") }}}
{{{ include("services/entities-mgnt-list-aside.js") }}}