// Templates
{{{ include("templates/templates.inc.js") }}}

// Controllers
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/entity-groups.js") }}}
{{{ include("controllers/entity-group-aside.js") }}}
{{{ include("controllers/entity-group-icon.js") }}}
{{{ include("controllers/entities.js") }}}
{{{ include("controllers/roles.js") }}}

// Models
{{{ include("models/accounting.js") }}}
{{{ include("models/entities-config.js") }}}
{{{ include("models/entity-group-aside-config.js") }}}
{{{ include("models/entity-group-config.js") }}}
{{{ include("models/entity-group-details-aside.js") }}}
{{{ include("models/entity-group-details.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}

// Services 
{{{ include("services/entity-group-data.js") }}}
{{{ include("services/entity-group-aside-data.js") }}}
{{{ include("services/entities-data.js") }}}
{{{ include("services/roles-data.js") }}}