{{{ include("controllers/change-user-type.js") }}}
{{{ include("controllers/user-details.js") }}}
{{{ include("controllers/external-user.js") }}}
{{{ include("controllers/existing-user.js") }}}
{{{ include("controllers/existing-emp-user.js") }}}
{{{ include("controllers/existing-user-noemail.js") }}}


{{{ include("filters/user-details-text.js") }}}

{{{ include("models/change-user-type-modal.js") }}}
{{{ include("models/change-user-type.js") }}}
{{{ include("models/custom-fields.js") }}}
{{{ include("models/form-config.js") }}}
{{{ include("models/user-details.js") }}}
{{{ include("models/external-user-modal.js") }}}
{{{ include("models/existing-emp-user-modal.js") }}}
{{{ include("models/existing-user-modal.js") }}}
{{{ include("models/existing-noemail-user-modal.js") }}}


{{{ include("services/user.js") }}}
{{{ include("services/third-party-idp.js") }}}
{{{ include("services/user-types.js") }}}
{{{ include("services/timezones.js") }}}
{{{ include("services/profile-contact-method.js") }}}
{{{ include("services/profile-industry-job-title.js") }}}
{{{ include("services/profile-phone-type.js") }}}
{{{ include("services/user-custom-field.js") }}}
{{{ include("services/external-user.js") }}}


{{{ include("templates/templates.inc.js") }}}
