
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-clone-rights.js") }}}
{{{ include("controllers/spndmgmt-clone-wrkflow.js") }}}



{{{ include("models/spndmgmt-clone-rights.js") }}}
{{{ include("models/spndmgmt-clone-wrkflow.js") }}}
{{{ include("models/spndmgmt-clone-wrkflowconfig.js") }}}



{{{ include("services/spndmgmt-clone-rights-data.js") }}}
{{{ include("services/spndmgmt-clone-rights-save.js") }}}






