
{{{ include("templates/templates.inc.js") }}}


{{{ include("controllers/user-mgmt-assign-role.js") }}}


{{{ include("services/user-mgmt-assign-tabs-data.js") }}}

{{{ include("models/user-mgmt-assign-tabs-menu.js") }}}

{{{ include("models/user-mgmt-assign-role-config.js") }}}

{{{ include("models/user-mgmt-assign-role.js") }}}

{{{ include("services/user-mgmt-assign-role.aside.js") }}}

{{{ include("services/user-mgmt-assign-role-tabs-manager.js") }}}

{{{ include("services/user-mgmt-assign-role-save.js") }}}

{{{ include("services/user-mgmt-assign-tabs-context.js") }}}













