{{{ include("controllers/user-details.js") }}}

{{{ include("filters/user-details-translator.js") }}}

{{{ include("models/add-persona-config.js") }}}
{{{ include("models/enable-switch-config.js") }}}
{{{ include("models/enterprise-role-config.js") }}}
{{{ include("models/notification-email-config.js") }}}
{{{ include("models/user-date-config.js") }}}
{{{ include("models/user-type-config.js") }}}
{{{ include("models/username-config.js") }}}
{{{ include("models/user-details-form-config.js") }}}
{{{ include("models/user-password-state.js") }}}

{{{ include("services/user-type.js") }}}

{{{ include("templates/templates.inc.js") }}}