
{{{ include("controllers/roles-and-rights.js") }}}

{{{ include("models/families-context.js") }}}
{{{ include("models/product-families-data.js") }}}
{{{ include("models/products.js") }}}
{{{ include("models/roles-rights-products.js") }}}
{{{ include("models/solutions-context.js") }}}
{{{ include("models/tabs-menu.js") }}}

{{{ include("services/products-data.js") }}}
{{{ include("services/tabs-data.js") }}}
