{{{ include("controllers/users.js") }}}

{{{ include("filters/users-translator.js") }}}

{{{ include("models/export-menu-config.js") }}}
{{{ include("models/user.js") }}}
{{{ include("models/users-filter-data.js") }}}
{{{ include("models/users-filter-form-config.js") }}}
{{{ include("models/users-filter.js") }}}
{{{ include("models/users-grid-actions.js") }}}
{{{ include("models/users-grid-config-factory.js") }}}
{{{ include("models/users-grid-config.js") }}}
{{{ include("models/users-grid.js") }}}


{{{ include("services/export-data.js") }}}
{{{ include("services/users-filter.js") }}}
{{{ include("services/users.js") }}}
{{{ include("services/users-custom-field.js") }}}
{{{ include("services/user-types.js") }}}

{{{ include("templates/templates.inc.js") }}}
