{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/employee-access.js") }}}
{{{ include("controllers/companies-admin-refresh-modal.js") }}}

{{{ include("models/search-config.js") }}}
{{{ include("models/employee-access.js") }}}
{{{ include("models/companies-actions.js") }}}
{{{ include("models/users-actions.js") }}}
{{{ include("models/companies-config.js") }}}
{{{ include("models/users-config.js") }}}
{{{ include("models/menu-config.js") }}}
{{{ include("models/employee-access-user.js") }}}
{{{ include("models/companies-action-modal.js") }}}

{{{ include("services/companies-admin-refresh-meg-modal.js") }}}
{{{ include("services/companies-admin-refresh-meg-save.js") }}}
{{{ include("services/companies-data.js") }}}
{{{ include("services/users-data.js") }}}

{{{ include("services/menu-data.js") }}}



