// Config

{{{ include("config/on-site.js") }}}

// Controllers

{{{ include("controllers/properties.js") }}}
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/property-groups.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/roles-radio.js") }}}

// Models

{{{ include("models/properties-config.js") }}}
{{{ include("models/on-site.js") }}}
{{{ include("models/property-groups-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/sync-manager.js") }}}
{{{ include("models/tabs-menu.js") }}}

// Services

{{{ include("services/properties-data.js") }}}
{{{ include("services/property-groups-data.js") }}}
{{{ include("services/roles-data.js") }}}

// Templates

{{{ include("templates/templates.inc.js") }}}
