
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-new-role.js") }}}

{{{ include("models/spndmgmt-new-role-config.js") }}}
{{{ include("models/spndmgmt-new-role-tabs-data.js") }}}
{{{ include("models/spndmgmt-new-role-tabs-menu.js") }}}
{{{ include("models/spndmgmt-new-role-template.js") }}}
{{{ include("models/spndmgmt-new-role.js") }}}


{{{ include("services/spndmgmt-new-role-save.js") }}}
{{{ include("services/spndmgmt-new-role-tabs-manager.js") }}}
{{{ include("services/spndmgmt-new-role.aside.js") }}}















