CREATE TABLE [UserManagement].[ProductPageType](
	[ProductPageTypeId] [int] IDENTITY(1,1) NOT NULL,	
	[Value] [nvarchar](200) NOT NULL,	
	[Description] [nvarchar](200) NULL
PRIMARY KEY CLUSTERED 
(
	[ProductPageTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO
