CREATE TABLE [Auth].[Clients] (
    [ClientId]                     INT             IDENTITY (1, 1) NOT NULL,  
    [ClientCode]                   NVARCHAR (200)  NOT NULL,
    [ClientName]                   NVARCHAR (200)  NOT NULL,
    [ClientUri]                    NVARCHAR (2000) NULL,
    [LogoUri]                      NVARCHAR (MAX)  NULL,
    [Flow]                         INT             NOT NULL,
    [LogoutUri]                    NVARCHAR (MAX)  NULL,
    [IdentityTokenLifetime]        INT             NOT NULL,
    [AccessTokenLifetime]          INT             NOT NULL,
    [AuthorizationCodeLifetime]    INT             NOT NULL,
    [AbsoluteRefreshTokenLifetime] INT             NOT NULL,
    [SlidingRefreshTokenLifetime]  INT             NOT NULL,
    [RefreshTokenUsage]            INT             NOT NULL,
	[RefreshTokenExpiration]       INT             NOT NULL,
    [AccessTokenType]              INT             NOT NULL,
	[UpdateAccessTokenOnRefresh]   BIT             NOT NULL,
	[Enabled]                      BIT             NOT NULL,
	[LogoutSessionRequired]        BIT             NOT NULL,
    [RequireSignOutPrompt]         BIT             NOT NULL,
    [AllowAccessToAllScopes]       BIT             NOT NULL,
	[AllowClientCredentialsOnly]   BIT             NOT NULL,
	[RequireConsent]               BIT             NOT NULL,
    [AllowRememberConsent]         BIT             NOT NULL,
    [EnableLocalLogin]             BIT             NOT NULL,
    [IncludeJwtId]                 BIT             NOT NULL,
    [AlwaysSendClientClaims]       BIT             NOT NULL,
    [PrefixClientClaims]           BIT             NOT NULL,
    [AllowAccessToAllGrantTypes]   BIT             NOT NULL,
    CONSTRAINT [PK_dbo.Clients] PRIMARY KEY CLUSTERED ([ClientId] ASC)
);

