//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace UnifiedLogin.SharedObjects.Product.RentersInsurance;

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://webservices.leasingdesk.com/", ConfigurationName = "RentersInsurance.LDClientAccessServiceSoap")]
public interface LDClientAccessServiceSoap
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/ValidateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<bool> ValidateUserAsync(string User, string Password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/ValidateUserDetails", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> ValidateUserDetailsAsync(RentersInsurance.ValidUserReq ValidateUser);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/MigrateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<string> MigrateUserAsync(RentersInsurance.MigrateUserrequest[] aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserInfo> GetUserAsync(string User);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/ChangeClaimStatus", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task ChangeClaimStatusAsync(string SystemIdentifier, bool IsLinked);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetUserByLogin", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> GetUserByLoginAsync(RentersInsurance.UserActionRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetUserByID", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> GetUserByIDAsync(RentersInsurance.UserActionRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/AddUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> AddUserAsync(RentersInsurance.AddUpdateUserRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/UpdateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UpdateUserAsync(RentersInsurance.AddUpdateUserRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/UnlockUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UnlockUserAsync(RentersInsurance.UserActionRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/DisableUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> DisableUserAsync(RentersInsurance.UserActionRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/EnableUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> EnableUserAsync(RentersInsurance.UserActionRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/UpdateUserPassword", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UpdateUserPasswordAsync(RentersInsurance.UpdatePasswordRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/CheckUserLogin", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.ErrorInfoType> CheckUserLoginAsync(RentersInsurance.CheckUserLoginExists UserLogin);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetListOfUserRoles", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.ListOfUserRolesResponse> GetListOfUserRolesAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetListOfPMC", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.ListOfPMCResponse> GetListOfPMCAsync();

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetUsersByPMC", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.ListOfUserResponse> GetUsersByPMCAsync(RentersInsurance.UserActionByPMCIDRequest aRequest);

    [System.ServiceModel.OperationContractAttribute(Action = "http://webservices.leasingdesk.com/GetListPropertyByPMCID", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AuthenticationType))]
    System.Threading.Tasks.Task<RentersInsurance.ListPropertyByPMCIDResponse> GetListPropertyByPMCIDAsync(int PMCID);
}

public class InsuranceService : IInsuranceService
{
    private readonly LDClientAccessServiceSoapClient _client;

    public InsuranceService()
    {
        _client = new LDClientAccessServiceSoapClient(LDClientAccessServiceSoapClient.EndpointConfiguration.LDClientAccessServiceSoap);
    }

    public Task<bool> ValidateUserAsync(string user, string password) => _client.ValidateUserAsync(user, password);
    public Task<GetUserByIDResponse> ValidateUserDetailsAsync(ValidUserReq validateUserRequest) => _client.ValidateUserDetailsAsync(validateUserRequest);
    public Task<string> MigrateUserAsync(MigrateUserrequest[] requests) => _client.MigrateUserAsync(requests);
    public Task<UserInfo> GetUserAsync(string user) => _client.GetUserAsync(user);
    public Task ChangeClaimStatusAsync(string systemIdentifier, bool isLinked) => _client.ChangeClaimStatusAsync(systemIdentifier, isLinked);
    public Task<GetUserByIDResponse> GetUserByLoginAsync(UserActionRequest request) => _client.GetUserByLoginAsync(request);
    public Task<GetUserByIDResponse> GetUserByIDAsync(UserActionRequest request) => _client.GetUserByIDAsync(request);
    public Task<UserAPIResponse> AddUserAsync(AddUpdateUserRequest request) => _client.AddUserAsync(request);
    public Task<UserAPIResponse> UpdateUserAsync(AddUpdateUserRequest request) => _client.UpdateUserAsync(request);
    public Task<UserAPIResponse> UnlockUserAsync(UserActionRequest request) => _client.UnlockUserAsync(request);
    public Task<UserAPIResponse> DisableUserAsync(UserActionRequest request) => _client.DisableUserAsync(request);
    public Task<UserAPIResponse> EnableUserAsync(UserActionRequest request) => _client.EnableUserAsync(request);
    public Task<UserAPIResponse> UpdateUserPasswordAsync(UpdatePasswordRequest request) => _client.UpdateUserPasswordAsync(request);
    public Task<ErrorInfoType> CheckUserLoginAsync(CheckUserLoginExists request) => _client.CheckUserLoginAsync(request);
    public Task<ListOfUserRolesResponse> GetListOfUserRolesAsync() => _client.GetListOfUserRolesAsync();
    public Task<ListOfPMCResponse> GetListOfPMCAsync() => _client.GetListOfPMCAsync();
    public Task<ListOfUserResponse> GetUsersByPMCAsync(UserActionByPMCIDRequest request) => _client.GetUsersByPMCAsync(request);
    public Task<ListPropertyByPMCIDResponse> GetListPropertyByPMCIDAsync(int pmcId) => _client.GetListPropertyByPMCIDAsync(pmcId);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ValidUserReq : AuthenticationType
{

    private string userField;

    private string pwdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
            this.RaisePropertyChanged("User");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Pwd
    {
        get
        {
            return this.pwdField;
        }
        set
        {
            this.pwdField = value;
            this.RaisePropertyChanged("Pwd");
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserActionByPMCIDRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckUserLoginExists))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdatePasswordRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AddUpdateUserRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(UserActionRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidUserReq))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class AuthenticationType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string loginField;

    private string passwordField;

    private int requestedByField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Login
    {
        get
        {
            return this.loginField;
        }
        set
        {
            this.loginField = value;
            this.RaisePropertyChanged("Login");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
            this.RaisePropertyChanged("Password");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int RequestedBy
    {
        get
        {
            return this.requestedByField;
        }
        set
        {
            this.requestedByField = value;
            this.RaisePropertyChanged("RequestedBy");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ListPropertyByPMCIDResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private UserProperty[] propertyListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    public UserProperty[] PropertyList
    {
        get
        {
            return this.propertyListField;
        }
        set
        {
            this.propertyListField = value;
            this.RaisePropertyChanged("PropertyList");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserProperty : object, System.ComponentModel.INotifyPropertyChanged
{

    private int propertyIDField;

    private string propertyNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int PropertyID
    {
        get
        {
            return this.propertyIDField;
        }
        set
        {
            this.propertyIDField = value;
            this.RaisePropertyChanged("PropertyID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string PropertyName
    {
        get
        {
            return this.propertyNameField;
        }
        set
        {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ListOfUserResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private UserInfo[] userListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    public UserInfo[] UserList
    {
        get
        {
            return this.userListField;
        }
        set
        {
            this.userListField = value;
            this.RaisePropertyChanged("UserList");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged
{

    private string userField;

    private string passwordField;

    private int userIdField;

    private bool isActiveField;

    private string firstNameField;

    private string lastNameField;

    private string emailField;

    private string roleField;

    private int roleIDField;

    private int failedCounterField;

    private string dateLastLoginField;

    private int companyIdField;

    private UserProperty[] propertyListField;

    private string propertyIDListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
            this.RaisePropertyChanged("User");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
            this.RaisePropertyChanged("Password");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool IsActive
    {
        get
        {
            return this.isActiveField;
        }
        set
        {
            this.isActiveField = value;
            this.RaisePropertyChanged("IsActive");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string FirstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
            this.RaisePropertyChanged("FirstName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string LastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
            this.RaisePropertyChanged("LastName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
            this.RaisePropertyChanged("Email");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public string Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
            this.RaisePropertyChanged("Role");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
    public int RoleID
    {
        get
        {
            return this.roleIDField;
        }
        set
        {
            this.roleIDField = value;
            this.RaisePropertyChanged("RoleID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
    public int FailedCounter
    {
        get
        {
            return this.failedCounterField;
        }
        set
        {
            this.failedCounterField = value;
            this.RaisePropertyChanged("FailedCounter");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
    public string DateLastLogin
    {
        get
        {
            return this.dateLastLoginField;
        }
        set
        {
            this.dateLastLoginField = value;
            this.RaisePropertyChanged("DateLastLogin");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
    public int CompanyId
    {
        get
        {
            return this.companyIdField;
        }
        set
        {
            this.companyIdField = value;
            this.RaisePropertyChanged("CompanyId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 12)]
    public UserProperty[] PropertyList
    {
        get
        {
            return this.propertyListField;
        }
        set
        {
            this.propertyListField = value;
            this.RaisePropertyChanged("PropertyList");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
    public string PropertyIDList
    {
        get
        {
            return this.propertyIDListField;
        }
        set
        {
            this.propertyIDListField = value;
            this.RaisePropertyChanged("PropertyIDList");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class PMC : object, System.ComponentModel.INotifyPropertyChanged
{

    private int companyIDField;

    private string companyNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int CompanyID
    {
        get
        {
            return this.companyIDField;
        }
        set
        {
            this.companyIDField = value;
            this.RaisePropertyChanged("CompanyID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string CompanyName
    {
        get
        {
            return this.companyNameField;
        }
        set
        {
            this.companyNameField = value;
            this.RaisePropertyChanged("CompanyName");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ListOfPMCResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private PMC[] pMCListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    public PMC[] PMCList
    {
        get
        {
            return this.pMCListField;
        }
        set
        {
            this.pMCListField = value;
            this.RaisePropertyChanged("PMCList");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserRole : object, System.ComponentModel.INotifyPropertyChanged
{

    private int roleIDField;

    private string roleNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int RoleID
    {
        get
        {
            return this.roleIDField;
        }
        set
        {
            this.roleIDField = value;
            this.RaisePropertyChanged("RoleID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string RoleName
    {
        get
        {
            return this.roleNameField;
        }
        set
        {
            this.roleNameField = value;
            this.RaisePropertyChanged("RoleName");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ListOfUserRolesResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private UserRole[] userRoleListField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
    public UserRole[] UserRoleList
    {
        get
        {
            return this.userRoleListField;
        }
        set
        {
            this.userRoleListField = value;
            this.RaisePropertyChanged("UserRoleList");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserAPIResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private int userIdField;

    private bool isSuccessField;

    private ErrorInfoType errorInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool IsSuccess
    {
        get
        {
            return this.isSuccessField;
        }
        set
        {
            this.isSuccessField = value;
            this.RaisePropertyChanged("IsSuccess");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public ErrorInfoType ErrorInfo
    {
        get
        {
            return this.errorInfoField;
        }
        set
        {
            this.errorInfoField = value;
            this.RaisePropertyChanged("ErrorInfo");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class ErrorInfoType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorCodeField;

    private string errorDescriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ErrorCode
    {
        get
        {
            return this.errorCodeField;
        }
        set
        {
            this.errorCodeField = value;
            this.RaisePropertyChanged("ErrorCode");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string ErrorDescription
    {
        get
        {
            return this.errorDescriptionField;
        }
        set
        {
            this.errorDescriptionField = value;
            this.RaisePropertyChanged("ErrorDescription");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class MigrateUserrequest : object, System.ComponentModel.INotifyPropertyChanged
{

    private string useridField;

    private string unifiedLoginUserNameField;

    private string usingUnifiedLoginField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string userid
    {
        get
        {
            return this.useridField;
        }
        set
        {
            this.useridField = value;
            this.RaisePropertyChanged("userid");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string unifiedLoginUserName
    {
        get
        {
            return this.unifiedLoginUserNameField;
        }
        set
        {
            this.unifiedLoginUserNameField = value;
            this.RaisePropertyChanged("unifiedLoginUserName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string usingUnifiedLogin
    {
        get
        {
            return this.usingUnifiedLoginField;
        }
        set
        {
            this.usingUnifiedLoginField = value;
            this.RaisePropertyChanged("usingUnifiedLogin");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class GetUserByIDResponse : object, System.ComponentModel.INotifyPropertyChanged
{

    private UserInfo userInfoField;

    private ErrorInfoType errorInfoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public UserInfo UserInfo
    {
        get
        {
            return this.userInfoField;
        }
        set
        {
            this.userInfoField = value;
            this.RaisePropertyChanged("UserInfo");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public ErrorInfoType ErrorInfo
    {
        get
        {
            return this.errorInfoField;
        }
        set
        {
            this.errorInfoField = value;
            this.RaisePropertyChanged("ErrorInfo");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserActionByPMCIDRequest : AuthenticationType
{

    private string companyIdField;

    private string filterTypeField;

    private int startRowField;

    private int resultsperpageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string CompanyId
    {
        get
        {
            return this.companyIdField;
        }
        set
        {
            this.companyIdField = value;
            this.RaisePropertyChanged("CompanyId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string FilterType
    {
        get
        {
            return this.filterTypeField;
        }
        set
        {
            this.filterTypeField = value;
            this.RaisePropertyChanged("FilterType");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int StartRow
    {
        get
        {
            return this.startRowField;
        }
        set
        {
            this.startRowField = value;
            this.RaisePropertyChanged("StartRow");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public int Resultsperpage
    {
        get
        {
            return this.resultsperpageField;
        }
        set
        {
            this.resultsperpageField = value;
            this.RaisePropertyChanged("Resultsperpage");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class CheckUserLoginExists : AuthenticationType
{

    private string userLoginField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string UserLogin
    {
        get
        {
            return this.userLoginField;
        }
        set
        {
            this.userLoginField = value;
            this.RaisePropertyChanged("UserLogin");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UpdatePasswordRequest : AuthenticationType
{

    private int userIdField;

    private string pwdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Pwd
    {
        get
        {
            return this.pwdField;
        }
        set
        {
            this.pwdField = value;
            this.RaisePropertyChanged("Pwd");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class AddUpdateUserRequest : AuthenticationType
{

    private UserInfo userField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public UserInfo User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
            this.RaisePropertyChanged("User");
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
public partial class UserActionRequest : AuthenticationType
{

    private int userIdField;

    private string userLoginField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string UserLogin
    {
        get
        {
            return this.userLoginField;
        }
        set
        {
            this.userLoginField = value;
            this.RaisePropertyChanged("UserLogin");
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface LDClientAccessServiceSoapChannel : RentersInsurance.LDClientAccessServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class LDClientAccessServiceSoapClient : System.ServiceModel.ClientBase<RentersInsurance.LDClientAccessServiceSoap>, RentersInsurance.LDClientAccessServiceSoap
{

    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public LDClientAccessServiceSoapClient(EndpointConfiguration endpointConfiguration) :
            base(LDClientAccessServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LDClientAccessServiceSoapClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LDClientAccessServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(LDClientAccessServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LDClientAccessServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(LDClientAccessServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public LDClientAccessServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public System.Threading.Tasks.Task<bool> ValidateUserAsync(string User, string Password)
    {
        return base.Channel.ValidateUserAsync(User, Password);
    }

    public System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> ValidateUserDetailsAsync(RentersInsurance.ValidUserReq ValidateUser)
    {
        return base.Channel.ValidateUserDetailsAsync(ValidateUser);
    }

    public System.Threading.Tasks.Task<string> MigrateUserAsync(RentersInsurance.MigrateUserrequest[] aRequest)
    {
        return base.Channel.MigrateUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserInfo> GetUserAsync(string User)
    {
        return base.Channel.GetUserAsync(User);
    }

    public System.Threading.Tasks.Task ChangeClaimStatusAsync(string SystemIdentifier, bool IsLinked)
    {
        return base.Channel.ChangeClaimStatusAsync(SystemIdentifier, IsLinked);
    }

    public System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> GetUserByLoginAsync(RentersInsurance.UserActionRequest aRequest)
    {
        return base.Channel.GetUserByLoginAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.GetUserByIDResponse> GetUserByIDAsync(RentersInsurance.UserActionRequest aRequest)
    {
        return base.Channel.GetUserByIDAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> AddUserAsync(RentersInsurance.AddUpdateUserRequest aRequest)
    {
        return base.Channel.AddUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UpdateUserAsync(RentersInsurance.AddUpdateUserRequest aRequest)
    {
        return base.Channel.UpdateUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UnlockUserAsync(RentersInsurance.UserActionRequest aRequest)
    {
        return base.Channel.UnlockUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> DisableUserAsync(RentersInsurance.UserActionRequest aRequest)
    {
        return base.Channel.DisableUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> EnableUserAsync(RentersInsurance.UserActionRequest aRequest)
    {
        return base.Channel.EnableUserAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.UserAPIResponse> UpdateUserPasswordAsync(RentersInsurance.UpdatePasswordRequest aRequest)
    {
        return base.Channel.UpdateUserPasswordAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.ErrorInfoType> CheckUserLoginAsync(RentersInsurance.CheckUserLoginExists UserLogin)
    {
        return base.Channel.CheckUserLoginAsync(UserLogin);
    }

    public System.Threading.Tasks.Task<RentersInsurance.ListOfUserRolesResponse> GetListOfUserRolesAsync()
    {
        return base.Channel.GetListOfUserRolesAsync();
    }

    public System.Threading.Tasks.Task<RentersInsurance.ListOfPMCResponse> GetListOfPMCAsync()
    {
        return base.Channel.GetListOfPMCAsync();
    }

    public System.Threading.Tasks.Task<RentersInsurance.ListOfUserResponse> GetUsersByPMCAsync(RentersInsurance.UserActionByPMCIDRequest aRequest)
    {
        return base.Channel.GetUsersByPMCAsync(aRequest);
    }

    public System.Threading.Tasks.Task<RentersInsurance.ListPropertyByPMCIDResponse> GetListPropertyByPMCIDAsync(int PMCID)
    {
        return base.Channel.GetListPropertyByPMCIDAsync(PMCID);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.LDClientAccessServiceSoap))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.LDClientAccessServiceSoap12))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
            httpBindingElement.AllowCookies = true;
            httpBindingElement.MaxBufferSize = int.MaxValue;
            httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.LDClientAccessServiceSoap))
        {
            return new System.ServiceModel.EndpointAddress("http://ri-ldwebapi-sat.realpage.com/LDClientAccessService.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.LDClientAccessServiceSoap12))
        {
            return new System.ServiceModel.EndpointAddress("http://ri-ldwebapi-sat.realpage.com/LDClientAccessService.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    public enum EndpointConfiguration
    {

        LDClientAccessServiceSoap,

        LDClientAccessServiceSoap12,
    }
}