// Config

// Controllers

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}

// Models

{{{ include("models/lead-2-lease.js") }}}
{{{ include("models/preset-role.js") }}}
{{{ include("models/properties-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}

// Services

{{{ include("services/properties-data.js") }}}
{{{ include("services/roles-data.js") }}}

// Templates

{{{ include("templates/templates.inc.js") }}}
