
{{{ include("controllers/manage-user.js") }}}

{{{ include("filters/manage-user-translator.js") }}}
{{{ include("data/user-types.js") }}}
{{{ include("data/user-states.js") }}}

{{{ include("models/manage-user.js") }}}
{{{ include("models/permissions.js") }}}
{{{ include("models/user-data.js") }}}
{{{ include("models/user-form-state.js") }}}
{{{ include("models/user.js") }}}
{{{ include("models/persona.js") }}}