
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/onesite-rights.js") }}}

{{{ include("models/onesite-products-config.js") }}}
{{{ include("models/onesite-products-menu.js") }}}
{{{ include("models/onesite-rights-actions.js") }}}
{{{ include("models/onesite-rights-config.js") }}}
{{{ include("models/onesite-rights.js") }}}

{{{ include("directives/onesite-actions.js") }}}

{{{ include("services/onesite-products.js") }}}
{{{ include("services/onesite-rights.js") }}}



