// Dependencies

{{{ include("../../../_common/standalone/js/data/external-links.js") }}}

// Controllers

{{{ include("controllers/carousel-product.js") }}}
{{{ include("controllers/carousel-resource.js") }}}
{{{ include("controllers/home.js") }}}
{{{ include("controllers/popover.js") }}}

{{{ include("directives/product-carousel-product.js") }}}

{{{ include("models/product-info-popover-config.js") }}}
{{{ include("models/products-carousel.js") }}}
{{{ include("models/resource-card-model.js") }}}
{{{ include("models/resources-carousel.js") }}}
{{{ include("models/user-resources-link-type.js") }}}

{{{ include("services/home.js") }}}

{{{ include("templates/templates.inc.js") }}}
