
{{{ include("templates/templates.inc.js") }}}


{{{ include("controllers/user-mgmt-new-role.js") }}}


{{{ include("models/user-mgmt-new-role-tabs-data.js") }}}

{{{ include("models/user-mgmt-new-role-tabs-menu.js") }}}

{{{ include("models/user-mgmt-new-role-config.js") }}}

{{{ include("models/user-mgmt-new-role.js") }}}

{{{ include("models/user-mgmt-new-role-template.js") }}}


{{{ include("services/user-mgmt-new-role.aside.js") }}}

{{{ include("services/user-mgmt-new-role-tabs-manager.js") }}}

{{{ include("services/user-mgmt-new-role-save.js") }}}















