
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/user-mgmt-clone-role.js") }}}

{{{ include("services/user-mgmt-clone-role-tabs-data.js") }}}

{{{ include("models/user-mgmt-clone-role-tabs-menu.js") }}}

{{{ include("models/user-mgmt-clone-role-form-config.js") }}}

{{{ include("models/user-mgmt-clone-role.js") }}}

{{{ include("services/user-mgmt-clone-role.aside.js") }}}

{{{ include("services/user-mgmt-clone-role-tabs-manager.js") }}}

{{{ include("services/user-mgmt-clone-role-save.js") }}}

{{{ include("services/user-mgmt-clone-role-tabs-context.js") }}}













