{{{ include("config/tabs.js") }}}
{{{ include("config/deposit-alternative.js") }}}

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties-grid.js") }}}
{{{ include("controllers/areas-grid.js") }}}
{{{ include("controllers/regions-grid.js") }}}


{{{ include("controllers/roles-grid.js") }}}
{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/notifications.js") }}}

{{{ include("models/properties-grid-config.js") }}}
{{{ include("models/areas-grid-config.js") }}}
{{{ include("models/regions-grid-config.js") }}}

{{{ include("models/role-model.js") }}}
{{{ include("models/roles-grid-config.js") }}}
{{{ include("models/tabs.js") }}}
{{{ include("models/deposit-alternative.js") }}}

{{{ include("services/properties-data.js") }}}
{{{ include("services/areas-data.js") }}}
{{{ include("services/regions-data.js") }}}
{{{ include("services/notifications-data.js") }}}


{{{ include("services/roles-data.js") }}}

{{{ include("templates/templates.inc.js") }}}
