
{{{ include("templates/templates.inc.js") }}}


{{{ include("controllers/assign-role.js") }}}

{{{ include("models/assign-role-form-config.js") }}}
{{{ include("models/assign-role-config.js") }}}
{{{ include("models/assign-role.js") }}}


{{{ include("services/assign-role-aside.js") }}}
{{{ include("services/assign-role-data.js") }}}
{{{ include("services/assign-role-save.js") }}}
{{{ include("services/assign-role-context.js") }}}













