
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/acct-delete-modal.js") }}}
{{{ include("controllers/acct-roles.js") }}}
{{{ include("controllers/acct-status-message.js") }}}


{{{ include("models/acct-assign-rights-products-data.js") }}}
{{{ include("models/acct-message-modal.js") }}}
{{{ include("models/acct-message.js") }}}
{{{ include("models/acct-roles-actions.js") }}}
{{{ include("models/acct-roles-config.js") }}}
{{{ include("models/acct-roles.js") }}}

{{{ include("directives/acct-actions.js") }}}

{{{ include("services/acct-assign-rights-products.js") }}}
{{{ include("services/acct-clone-role.js") }}}
{{{ include("services/acct-delete-role.js") }}}
{{{ include("services/acct-roles.js") }}}



