{{{ include("controllers/user-profile.js") }}}

{{{ include("filters/user-profile-text.js") }}}

{{{ include("models/contact-method-config.js") }}}
{{{ include("models/job-title-config.js") }}}
{{{ include("models/phone-number-config.js") }}}
{{{ include("models/usage-type-config.js") }}}
{{{ include("models/form-config.js") }}}
{{{ include("models/user-profile.js") }}}

{{{ include("services/user-profile.js") }}}
{{{ include("services/contact-method.js") }}}
{{{ include("services/job-title.js") }}}
{{{ include("services/phone-usage-type.js") }}}

{{{ include("templates/templates.inc.js") }}}
