// External Modules

{{{ include("../../lib/angular/strap/js/scripts.js") }}}

// RealPage Modules

{{{ include("../../lib/realpage/common/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-text-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-select-menu-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/language/js/scripts.js") }}}
{{{ include("../../lib/realpage/page-title/js/scripts.js") }}}

// New User Setup Modules

{{{ include("base/_bundle.inc") }}}
{{{ include("config/_bundle.inc") }}}
{{{ include("controllers/_bundle.inc") }}}
{{{ include("models/_bundle.inc") }}}

// Shared Modules

{{{ include("../../../../shared-ui-src/_common/js/_bundle.inc") }}}
