//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RP.Enterprise.Subsystem.ProductLauncher.Component.SharedObjects.Product.RentersInsurance {
    using Newtonsoft.Json;
    using System.Diagnostics.CodeAnalysis;
    using System.Net;

    [ExcludeFromCodeCoverage]

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LDClientAccessServiceSoap", Namespace="http://webservices.leasingdesk.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationType))]
    public partial class InsuranceService : System.Web.Services.Protocols.SoapHttpClientProtocol, IInsuranceService
    {
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback MigrateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeClaimStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnlockUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisableUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnableUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfUserRolesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfPMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUsersByPMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListPropertyByPMCIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public InsuranceService() {
            //this.Url = global::RentersInsuranceService.Properties.Settings.Default.RentersInsuranceService_com_realpage_ldweb_sat_LDClientAccessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event ValidateUserDetailsCompletedEventHandler ValidateUserDetailsCompleted;
        
        /// <remarks/>
        public event MigrateUserCompletedEventHandler MigrateUserCompleted;
        
        /// <remarks/>
        public event GetUserCompletedEventHandler GetUserCompleted;
        
        /// <remarks/>
        public event ChangeClaimStatusCompletedEventHandler ChangeClaimStatusCompleted;
        
        /// <remarks/>
        public event GetUserByLoginCompletedEventHandler GetUserByLoginCompleted;
        
        /// <remarks/>
        public event GetUserByIDCompletedEventHandler GetUserByIDCompleted;
        
        /// <remarks/>
        public event AddUserCompletedEventHandler AddUserCompleted;
        
        /// <remarks/>
        public event UpdateUserCompletedEventHandler UpdateUserCompleted;
        
        /// <remarks/>
        public event UnlockUserCompletedEventHandler UnlockUserCompleted;
        
        /// <remarks/>
        public event DisableUserCompletedEventHandler DisableUserCompleted;
        
        /// <remarks/>
        public event EnableUserCompletedEventHandler EnableUserCompleted;
        
        /// <remarks/>
        public event UpdateUserPasswordCompletedEventHandler UpdateUserPasswordCompleted;
        
        /// <remarks/>
        public event GetListOfUserRolesCompletedEventHandler GetListOfUserRolesCompleted;
        
        /// <remarks/>
        public event GetListOfPMCCompletedEventHandler GetListOfPMCCompleted;
        
        /// <remarks/>
        public event GetUsersByPMCCompletedEventHandler GetUsersByPMCCompleted;
        
        /// <remarks/>
        public event GetListPropertyByPMCIDCompletedEventHandler GetListPropertyByPMCIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/ValidateUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUser(string User, string Password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        User,
                        Password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string User, string Password) {
            this.ValidateUserAsync(User, Password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string User, string Password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        User,
                        Password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/ValidateUserDetails", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUserByIDResponse ValidateUserDetails([System.Xml.Serialization.XmlElementAttribute("ValidateUser")] ValidUserReq ValidateUser1) {
            object[] results = this.Invoke("ValidateUserDetails", new object[] {
                        ValidateUser1});
            return ((GetUserByIDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserDetailsAsync(ValidUserReq ValidateUser1) {
            this.ValidateUserDetailsAsync(ValidateUser1, null);
        }
        
        /// <remarks/>
        public void ValidateUserDetailsAsync(ValidUserReq ValidateUser1, object userState) {
            if ((this.ValidateUserDetailsOperationCompleted == null)) {
                this.ValidateUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserDetailsOperationCompleted);
            }
            this.InvokeAsync("ValidateUserDetails", new object[] {
                        ValidateUser1}, this.ValidateUserDetailsOperationCompleted, userState);
        }
        
        private void OnValidateUserDetailsOperationCompleted(object arg) {
            if ((this.ValidateUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserDetailsCompleted(this, new ValidateUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/MigrateUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MigrateUser(MigrateUserrequest[] aRequest) {
            object[] results = this.Invoke("MigrateUser", new object[] {
                        aRequest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MigrateUserAsync(MigrateUserrequest[] aRequest) {
            this.MigrateUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void MigrateUserAsync(MigrateUserrequest[] aRequest, object userState) {
            if ((this.MigrateUserOperationCompleted == null)) {
                this.MigrateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMigrateUserOperationCompleted);
            }
            this.InvokeAsync("MigrateUser", new object[] {
                        aRequest}, this.MigrateUserOperationCompleted, userState);
        }
        
        private void OnMigrateUserOperationCompleted(object arg) {
            if ((this.MigrateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MigrateUserCompleted(this, new MigrateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserInfo GetUser(string User) {
            object[] results = this.Invoke("GetUser", new object[] {
                        User});
            return ((UserInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserAsync(string User) {
            this.GetUserAsync(User, null);
        }
        
        /// <remarks/>
        public void GetUserAsync(string User, object userState) {
            if ((this.GetUserOperationCompleted == null)) {
                this.GetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserOperationCompleted);
            }
            this.InvokeAsync("GetUser", new object[] {
                        User}, this.GetUserOperationCompleted, userState);
        }
        
        private void OnGetUserOperationCompleted(object arg) {
            if ((this.GetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserCompleted(this, new GetUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/ChangeClaimStatus", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ChangeClaimStatus(string SystemIdentifier, bool IsLinked) {
            this.Invoke("ChangeClaimStatus", new object[] {
                        SystemIdentifier,
                        IsLinked});
        }
        
        /// <remarks/>
        public void ChangeClaimStatusAsync(string SystemIdentifier, bool IsLinked) {
            this.ChangeClaimStatusAsync(SystemIdentifier, IsLinked, null);
        }
        
        /// <remarks/>
        public void ChangeClaimStatusAsync(string SystemIdentifier, bool IsLinked, object userState) {
            if ((this.ChangeClaimStatusOperationCompleted == null)) {
                this.ChangeClaimStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeClaimStatusOperationCompleted);
            }
            this.InvokeAsync("ChangeClaimStatus", new object[] {
                        SystemIdentifier,
                        IsLinked}, this.ChangeClaimStatusOperationCompleted, userState);
        }
        
        private void OnChangeClaimStatusOperationCompleted(object arg) {
            if ((this.ChangeClaimStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeClaimStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetUserByLogin", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUserByIDResponse GetUserByLogin(UserActionRequest aRequest) {
            object[] results = this.Invoke("GetUserByLogin", new object[] {
                        aRequest});
            return ((GetUserByIDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByLoginAsync(UserActionRequest aRequest) {
            this.GetUserByLoginAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void GetUserByLoginAsync(UserActionRequest aRequest, object userState) {
            if ((this.GetUserByLoginOperationCompleted == null)) {
                this.GetUserByLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByLoginOperationCompleted);
            }
            this.InvokeAsync("GetUserByLogin", new object[] {
                        aRequest}, this.GetUserByLoginOperationCompleted, userState);
        }
        
        private void OnGetUserByLoginOperationCompleted(object arg) {
            if ((this.GetUserByLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByLoginCompleted(this, new GetUserByLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetUserByID", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GetUserByIDResponse GetUserByID(UserActionRequest aRequest) {
            object[] results = this.Invoke("GetUserByID", new object[] {
                        aRequest});
            return ((GetUserByIDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByIDAsync(UserActionRequest aRequest) {
            this.GetUserByIDAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void GetUserByIDAsync(UserActionRequest aRequest, object userState) {
            if ((this.GetUserByIDOperationCompleted == null)) {
                this.GetUserByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByIDOperationCompleted);
            }
            this.InvokeAsync("GetUserByID", new object[] {
                        aRequest}, this.GetUserByIDOperationCompleted, userState);
        }
        
        private void OnGetUserByIDOperationCompleted(object arg) {
            if ((this.GetUserByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByIDCompleted(this, new GetUserByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/AddUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse AddUser(AddUpdateUserRequest aRequest) {
            object[] results = this.Invoke("AddUser", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AddUserAsync(AddUpdateUserRequest aRequest) {
            this.AddUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void AddUserAsync(AddUpdateUserRequest aRequest, object userState) {
            if ((this.AddUserOperationCompleted == null)) {
                this.AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddUserOperationCompleted);
            }
            this.InvokeAsync("AddUser", new object[] {
                        aRequest}, this.AddUserOperationCompleted, userState);
        }
        
        private void OnAddUserOperationCompleted(object arg) {
            if ((this.AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddUserCompleted(this, new AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/UpdateUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse UpdateUser(AddUpdateUserRequest aRequest) {
            object[] results = this.Invoke("UpdateUser", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserAsync(AddUpdateUserRequest aRequest) {
            this.UpdateUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void UpdateUserAsync(AddUpdateUserRequest aRequest, object userState) {
            if ((this.UpdateUserOperationCompleted == null)) {
                this.UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserOperationCompleted);
            }
            this.InvokeAsync("UpdateUser", new object[] {
                        aRequest}, this.UpdateUserOperationCompleted, userState);
        }
        
        private void OnUpdateUserOperationCompleted(object arg) {
            if ((this.UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserCompleted(this, new UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/UnlockUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse UnlockUser(UserActionRequest aRequest) {
            object[] results = this.Invoke("UnlockUser", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UnlockUserAsync(UserActionRequest aRequest) {
            this.UnlockUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void UnlockUserAsync(UserActionRequest aRequest, object userState) {
            if ((this.UnlockUserOperationCompleted == null)) {
                this.UnlockUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnlockUserOperationCompleted);
            }
            this.InvokeAsync("UnlockUser", new object[] {
                        aRequest}, this.UnlockUserOperationCompleted, userState);
        }
        
        private void OnUnlockUserOperationCompleted(object arg) {
            if ((this.UnlockUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnlockUserCompleted(this, new UnlockUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/DisableUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse DisableUser(UserActionRequest aRequest) {
            object[] results = this.Invoke("DisableUser", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/CheckUserLogin", RequestNamespace = "http://webservices.leasingdesk.com/", ResponseNamespace = "http://webservices.leasingdesk.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ErrorInfoType CheckUserLogin(CheckUserLogin UserLogin)
        {
            object[] results = this.Invoke("CheckUserLogin", new object[] {
                        UserLogin});
            return ((ErrorInfoType)(results[0]));
        }

        /// <remarks/>
        public void DisableUserAsync(UserActionRequest aRequest) {
            this.DisableUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void DisableUserAsync(UserActionRequest aRequest, object userState) {
            if ((this.DisableUserOperationCompleted == null)) {
                this.DisableUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisableUserOperationCompleted);
            }
            this.InvokeAsync("DisableUser", new object[] {
                        aRequest}, this.DisableUserOperationCompleted, userState);
        }
        
        private void OnDisableUserOperationCompleted(object arg) {
            if ((this.DisableUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisableUserCompleted(this, new DisableUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/EnableUser", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse EnableUser(UserActionRequest aRequest) {
            object[] results = this.Invoke("EnableUser", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void EnableUserAsync(UserActionRequest aRequest) {
            this.EnableUserAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void EnableUserAsync(UserActionRequest aRequest, object userState) {
            if ((this.EnableUserOperationCompleted == null)) {
                this.EnableUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnableUserOperationCompleted);
            }
            this.InvokeAsync("EnableUser", new object[] {
                        aRequest}, this.EnableUserOperationCompleted, userState);
        }
        
        private void OnEnableUserOperationCompleted(object arg) {
            if ((this.EnableUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnableUserCompleted(this, new EnableUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/UpdateUserPassword", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserAPIResponse UpdateUserPassword(UpdatePasswordRequest aRequest) {
            object[] results = this.Invoke("UpdateUserPassword", new object[] {
                        aRequest});
            return ((UserAPIResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateUserPasswordAsync(UpdatePasswordRequest aRequest) {
            this.UpdateUserPasswordAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void UpdateUserPasswordAsync(UpdatePasswordRequest aRequest, object userState) {
            if ((this.UpdateUserPasswordOperationCompleted == null)) {
                this.UpdateUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateUserPasswordOperationCompleted);
            }
            this.InvokeAsync("UpdateUserPassword", new object[] {
                        aRequest}, this.UpdateUserPasswordOperationCompleted, userState);
        }
        
        private void OnUpdateUserPasswordOperationCompleted(object arg) {
            if ((this.UpdateUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateUserPasswordCompleted(this, new UpdateUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetListOfUserRoles", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOfUserRolesResponse GetListOfUserRoles() {
            object[] results = this.Invoke("GetListOfUserRoles", new object[0]);
            return ((ListOfUserRolesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfUserRolesAsync() {
            this.GetListOfUserRolesAsync(null);
        }
        
        /// <remarks/>
        public void GetListOfUserRolesAsync(object userState) {
            if ((this.GetListOfUserRolesOperationCompleted == null)) {
                this.GetListOfUserRolesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfUserRolesOperationCompleted);
            }
            this.InvokeAsync("GetListOfUserRoles", new object[0], this.GetListOfUserRolesOperationCompleted, userState);
        }
        
        private void OnGetListOfUserRolesOperationCompleted(object arg) {
            if ((this.GetListOfUserRolesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfUserRolesCompleted(this, new GetListOfUserRolesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetListOfPMC", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOfPMCResponse GetListOfPMC() {
            object[] results = this.Invoke("GetListOfPMC", new object[0]);
            return ((ListOfPMCResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfPMCAsync() {
            this.GetListOfPMCAsync(null);
        }
        
        /// <remarks/>
        public void GetListOfPMCAsync(object userState) {
            if ((this.GetListOfPMCOperationCompleted == null)) {
                this.GetListOfPMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfPMCOperationCompleted);
            }
            this.InvokeAsync("GetListOfPMC", new object[0], this.GetListOfPMCOperationCompleted, userState);
        }
        
        private void OnGetListOfPMCOperationCompleted(object arg) {
            if ((this.GetListOfPMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfPMCCompleted(this, new GetListOfPMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetUsersByPMC", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListOfUserResponse GetUsersByPMC(UserActionByPMCIDRequest aRequest) {
            object[] results = this.Invoke("GetUsersByPMC", new object[] {
                        aRequest});
            return ((ListOfUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetUsersByPMCAsync(UserActionByPMCIDRequest aRequest) {
            this.GetUsersByPMCAsync(aRequest, null);
        }
        
        /// <remarks/>
        public void GetUsersByPMCAsync(UserActionByPMCIDRequest aRequest, object userState) {
            if ((this.GetUsersByPMCOperationCompleted == null)) {
                this.GetUsersByPMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUsersByPMCOperationCompleted);
            }
            this.InvokeAsync("GetUsersByPMC", new object[] {
                        aRequest}, this.GetUsersByPMCOperationCompleted, userState);
        }
        
        private void OnGetUsersByPMCOperationCompleted(object arg) {
            if ((this.GetUsersByPMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUsersByPMCCompleted(this, new GetUsersByPMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.leasingdesk.com/GetListPropertyByPMCID", RequestNamespace="http://webservices.leasingdesk.com/", ResponseNamespace="http://webservices.leasingdesk.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListPropertyByPMCIDResponse GetListPropertyByPMCID(int PMCID) {
            object[] results = this.Invoke("GetListPropertyByPMCID", new object[] {
                        PMCID});
            return ((ListPropertyByPMCIDResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetListPropertyByPMCIDAsync(int PMCID) {
            this.GetListPropertyByPMCIDAsync(PMCID, null);
        }
        
        /// <remarks/>
        public void GetListPropertyByPMCIDAsync(int PMCID, object userState) {
            if ((this.GetListPropertyByPMCIDOperationCompleted == null)) {
                this.GetListPropertyByPMCIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListPropertyByPMCIDOperationCompleted);
            }
            this.InvokeAsync("GetListPropertyByPMCID", new object[] {
                        PMCID}, this.GetListPropertyByPMCIDOperationCompleted, userState);
        }
        
        private void OnGetListPropertyByPMCIDOperationCompleted(object arg) {
            if ((this.GetListPropertyByPMCIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListPropertyByPMCIDCompleted(this, new GetListPropertyByPMCIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ValidUserReq : AuthenticationType {
        
        private string userField;
        
        private string pwdField;
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ListOfUserResponse {
        
        private UserInfo[] userListField;
        
        /// <remarks/>
        public UserInfo[] UserList {
            get {
                return this.userListField;
            }
            set {
                this.userListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UserInfo {
        
        private string userField;
        
        private string passwordField;
        
        private int userIdField;
        
        private bool isActiveField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string roleField;
        
        private int roleIDField;
        
        private int failedCounterField;
        
        private string dateLastLoginField;
        
        private int companyIdField;
        
        private UserProperty[] propertyListField;
        
        private string propertyIDListField;
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public int FailedCounter {
            get {
                return this.failedCounterField;
            }
            set {
                this.failedCounterField = value;
            }
        }
        
        /// <remarks/>
        public string DateLastLogin {
            get {
                return this.dateLastLoginField;
            }
            set {
                this.dateLastLoginField = value;
            }
        }
        
        /// <remarks/>
        public int CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public UserProperty[] PropertyList {
            get {
                return this.propertyListField;
            }
            set {
                this.propertyListField = value;
            }
        }

        /// <remarks/>
        public string PropertyIDList
        {
            get
            {
                return this.propertyIDListField;
            }
            set
            {
                this.propertyIDListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
     public partial class UserProperty {
        
        private int propertyIDField;
        
        private string propertyNameField;
        
        /// <remarks/>
        public int PropertyID {
            get {
                return this.propertyIDField;
            }
            set {
                this.propertyIDField = value;
            }
        }
        
        /// <remarks/>
        public string PropertyName {
            get {
                return this.propertyNameField;
            }
            set {
                this.propertyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ListPropertyByPMCIDResponse {
        
        private UserProperty[] propertyListField;
        
        /// <remarks/>
        public UserProperty[] PropertyList {
            get {
                return this.propertyListField;
            }
            set {
                this.propertyListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class PMC {
        
        private int companyIDField;
        
        private string companyNameField;
        
        /// <remarks/>
        public int CompanyID {
            get {
                return this.companyIDField;
            }
            set {
                this.companyIDField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ListOfPMCResponse {
        
        private PMC[] pMCListField;
        
        /// <remarks/>
        public PMC[] PMCList {
            get {
                return this.pMCListField;
            }
            set {
                this.pMCListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UserRole {
        
        private int roleIDField;
        
        private string roleNameField;
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ListOfUserRolesResponse {
        
        private UserRole[] userRoleListField;
        
        /// <remarks/>
        public UserRole[] UserRoleList {
            get {
                return this.userRoleListField;
            }
            set {
                this.userRoleListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UserAPIResponse {
        
        private int userIdField;
        
        private bool isSuccessField;
        
        private ErrorInfoType errorInfoField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        public ErrorInfoType ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class ErrorInfoType {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class MigrateUserrequest {
        
        private string useridField;
        
        private string unifiedLoginUserNameField;
        
        private string usingUnifiedLoginField;
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public string unifiedLoginUserName {
            get {
                return this.unifiedLoginUserNameField;
            }
            set {
                this.unifiedLoginUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string usingUnifiedLogin {
            get {
                return this.usingUnifiedLoginField;
            }
            set {
                this.usingUnifiedLoginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class GetUserByIDResponse {
        
        private UserInfo userInfoField;
        
        private ErrorInfoType errorInfoField;
        
        /// <remarks/>
        public UserInfo UserInfo {
            get {
                return this.userInfoField;
            }
            set {
                this.userInfoField = value;
            }
        }
        
        /// <remarks/>
        public ErrorInfoType ErrorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserActionByPMCIDRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdatePasswordRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddUpdateUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserActionRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidUserReq))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class AuthenticationType {

        private string loginField;

        private string passwordField;

        private int requestedByField;

        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }

        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public int RequestedBy {
            get {
                return this.requestedByField;
            }
            set {
                this.requestedByField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdatePasswordRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddUpdateUserRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserActionRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UserActionByPMCIDRequest : AuthenticationType {
        
        private string companyIdField;
        
        private string filterTypeField;
        
        private int startRowField;
        
        private int resultsperpageField;
        
        /// <remarks/>
        public string CompanyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string FilterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
            }
        }
        
        /// <remarks/>
        public int StartRow {
            get {
                return this.startRowField;
            }
            set {
                this.startRowField = value;
            }
        }
        
        /// <remarks/>
        public int Resultsperpage {
            get {
                return this.resultsperpageField;
            }
            set {
                this.resultsperpageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UpdatePasswordRequest : AuthenticationType {
        
        private int userIdField;
        
        private string pwdField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class AddUpdateUserRequest : AuthenticationType {
        
        private UserInfo userField;
        
        /// <remarks/>
        public UserInfo User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.leasingdesk.com/")]
    public partial class UserActionRequest : AuthenticationType {
        
        private int userIdField;
        
        private string userLoginField;
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string UserLogin {
            get {
                return this.userLoginField;
            }
            set {
                this.userLoginField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://webservices.leasingdesk.com/")]
    public class CheckUserLogin : AuthenticationType
    {
        private string userLoginField;

        public string UserLogin
        {
            get
            {
                return this.userLoginField;
            }
            set
            {
                this.userLoginField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ValidateUserDetailsCompletedEventHandler(object sender, ValidateUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserByIDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserByIDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void MigrateUserCompletedEventHandler(object sender, MigrateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MigrateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MigrateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetUserCompletedEventHandler(object sender, GetUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ChangeClaimStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetUserByLoginCompletedEventHandler(object sender, GetUserByLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserByIDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserByIDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetUserByIDCompletedEventHandler(object sender, GetUserByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetUserByIDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetUserByIDResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void AddUserCompletedEventHandler(object sender, AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateUserCompletedEventHandler(object sender, UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UnlockUserCompletedEventHandler(object sender, UnlockUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnlockUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnlockUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void DisableUserCompletedEventHandler(object sender, DisableUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisableUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisableUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void EnableUserCompletedEventHandler(object sender, EnableUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnableUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnableUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void UpdateUserPasswordCompletedEventHandler(object sender, UpdateUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserAPIResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserAPIResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetListOfUserRolesCompletedEventHandler(object sender, GetListOfUserRolesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfUserRolesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfUserRolesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOfUserRolesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOfUserRolesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetListOfPMCCompletedEventHandler(object sender, GetListOfPMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfPMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfPMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOfPMCResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOfPMCResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetUsersByPMCCompletedEventHandler(object sender, GetUsersByPMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUsersByPMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUsersByPMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListOfUserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListOfUserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetListPropertyByPMCIDCompletedEventHandler(object sender, GetListPropertyByPMCIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListPropertyByPMCIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListPropertyByPMCIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListPropertyByPMCIDResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListPropertyByPMCIDResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591