{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/onesite-product-access.js") }}}
{{{ include("controllers/onesite-properties-roles.js") }}}
{{{ include("controllers/properties-grid.js") }}}
{{{ include("controllers/rights-list-aside.js") }}}
{{{ include("controllers/role-info-icon.js") }}}
{{{ include("controllers/roles-grid.js") }}}

{{{ include("models/onesite-production-tabs-menu.js") }}}
{{{ include("models/onesite-rights.js") }}}
{{{ include("models/onesite.js") }}}
{{{ include("models/properties-grid.js") }}}
{{{ include("models/rights-list-aside.js") }}}
{{{ include("models/rights-list-grid.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/side-menu-config.js") }}}

{{{ include("services/onesite-properties.js") }}}
{{{ include("services/onesite-rights-aside.js") }}}
{{{ include("services/onesite-roles.js") }}}
{{{ include("services/onesite-tabs-data.js") }}}
