
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-assign-rights.js") }}}
{{{ include("controllers/spndmgmt-assign-workflow.js") }}}



{{{ include("models/spndmgmt-assign-rights.js") }}}
{{{ include("models/spndmgmt-assign-workflow.js") }}}
{{{ include("models/spndmgmt-assign-workflow-config.js") }}}



{{{ include("services/spndmgmt-assign-rights-data.js") }}}
{{{ include("services/spndmgmt-assign-rights-save.js") }}}







