{{{ include("templates/templates.inc.js") }}}

{{{ include("config/client-portal.js") }}}

{{{ include("controllers/client-portal-product-access.js") }}}
{{{ include("controllers/client-portal-properties-roles.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/role-radio.js") }}}
{{{ include("controllers/property-radio.js") }}}

{{{ include("models/properties-grid.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/client-portal.js") }}}

{{{ include("models/data-json.js") }}}
{{{ include("models/config-data-model.js") }}}
{{{ include("models/grid-factory.js") }}}
{{{ include("models/config-model.js") }}}


{{{ include("services/client-portal-tabs-data.js") }}}
{{{ include("services/properties-data.js") }}}
{{{ include("services/roles-data.js") }}}