{{{ include("templates/templates.inc.js") }}}

{{{ include("config/integration-marketplace.js") }}}

{{{ include("controllers/rights-list-aside.js") }}}
{{{ include("controllers/role-info-icon.js") }}}
{{{ include("controllers/roles-radio.js") }}}
{{{ include("controllers/roles.js") }}}
{{{ include("controllers/integration-marketplace-product-access.js") }}}
{{{ include("controllers/integration-marketplace-properties-roles.js") }}}

{{{ include("models/rights-list-aside.js") }}}
{{{ include("models/rights-list-grid.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/side-menu-config.js") }}}
{{{ include("models/integration-marketplace-production-tabs-menu.js") }}}
{{{ include("models/integration-marketplace-rights.js") }}}
{{{ include("models/integration-marketplace-roles.js") }}}



{{{ include("services/roles-data.js") }}}
{{{ include("services/integration-marketplace-rights-aside.js") }}}
{{{ include("services/integration-marketplace-tabs-data.js") }}}
