// Templates
{{{ include("templates/templates.inc.js") }}}

// Config

// Controllers
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}

// Models
{{{ include("models/properties-config.js") }}}
{{{ include("models/property-group-config.js") }}}
{{{ include("models/regions-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/utility-management.js") }}}

// Services
{{{ include("services/property-group-data.js") }}}
{{{ include("services/properties-data.js") }}}
{{{ include("services/regions-data.js") }}}
{{{ include("services/roles-data.js") }}}
