
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-new-rights.js") }}}
{{{ include("controllers/spndmgmt-new-wrkflow.js") }}}


{{{ include("models/spndmgmt-new-rights.js") }}}
{{{ include("models/spndmgmt-new-rights-workflow-config.js") }}}
{{{ include("models/spndmgmt-new-workflow.js") }}}


{{{ include("services/spndmgmt-new-rights-data.js") }}}
{{{ include("services/spndmgmt-new-rights-save.js") }}}






