// RealPage Modules

{{{ include("../../lib/realpage/common/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-checkbox/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-input-text-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/form-select-menu-v1/js/scripts.js") }}}
{{{ include("../../lib/realpage/language/js/scripts.js") }}}

// Identity Modules

{{{ include("base/_bundle.inc") }}}
{{{ include("config/_bundle.inc") }}}
{{{ include("controllers/_bundle.inc") }}}
{{{ include("services/_bundle.inc") }}}
{{{ include("directives/_bundle.inc") }}}

// Shared Modules

{{{ include("../../../../shared-ui-src/_common/js/_bundle.inc") }}}

// Identity Shared Modules

{{{ include("../../_common/identity/_bundle.inc") }}}
