using Microsoft.OpenApi;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.Text.Json.Nodes;
using UnifiedLogin.SharedObjects.Base;

namespace UnifiedLogin.Core.Filters
{
    /// <summary>
    /// Replaces all auto-generated RequestParameter parameters with explicit datafilter.* parameters.
    /// </summary>
    public class RequestParameterOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var hasRequestParameter = context.ApiDescription.ParameterDescriptions
                .Any(p => p.Type == typeof(RequestParameter));

            if (!hasRequestParameter)
                return;

            // ✅ Remove ALL parameters that come from RequestParameter expansion
            // These are generated by Swagger introspecting the RequestParameter class properties
            var toRemove = operation.Parameters
                .Where(p =>
                    p.Name.Equals("FilterBy", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("SortBy", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("datafilter", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("Pages.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("FilterBy.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("SortBy.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Contains("OrderedColumnNames", StringComparison.OrdinalIgnoreCase))
                .ToList();

            foreach (var p in toRemove)
            {
                operation.Parameters.Remove(p);
            }

            // ✅ Add custom parameters matching .NET Framework 4.8 behavior (all strings)
            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.filterBy",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Filter criteria as JSON. Example: {\"status\":\"1\",\"offsetMinutes\":\"0\"}",
                Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.String,
                    Example = JsonValue.Create("{\"status\":\"1\"}")
                }
            });

            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.sortBy",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Sort criteria as JSON. Example: {\"firstName\":\"ASC\"}",
                Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.String,
                    Example = JsonValue.Create("{\"firstName\":\"ASC\"}")
                }
            });

            // ✅ CRITICAL FIX: Change these to STRING type to match .NET Framework 4.8
            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.pages.startRow",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Starting row index for pagination (default: 1)",
                Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.String, // ✅ Changed from "integer" to "string"
                    Example = JsonValue.Create("1")
                }
            });

            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.pages.resultsPerPage",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Number of results per page (default: 100)",
                Schema = new OpenApiSchema
                {
                    Type = JsonSchemaType.String, // ✅ Changed from "integer" to "string"
                    Example = JsonValue.Create("100")
                }
            });
        }
    }
}
