using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;
using UnifiedLogin.SharedObjects.Base;

namespace UnifiedLogin.Core.Filters
{
    /// <summary>
    /// Replaces all auto-generated RequestParameter parameters with explicit datafilter.* parameters.
    /// </summary>
    public class RequestParameterOperationFilter : IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var hasRequestParameter = context.ApiDescription.ParameterDescriptions
                .Any(p => p.Type == typeof(RequestParameter));

            if (!hasRequestParameter)
                return;

            // ✅ Remove ALL parameters that come from RequestParameter expansion
            // These are generated by Swagger introspecting the RequestParameter class properties
            var toRemove = operation.Parameters
                .Where(p =>
                    p.Name.Equals("FilterBy", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("SortBy", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Equals("datafilter", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("Pages.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("FilterBy.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.StartsWith("SortBy.", StringComparison.OrdinalIgnoreCase) ||
                    p.Name.Contains("OrderedColumnNames", StringComparison.OrdinalIgnoreCase) ||
                    // ✅ Also remove any that use the RequestParameter schema ref
                    p.Schema?.Reference?.Id?.Contains("RequestParameter", StringComparison.OrdinalIgnoreCase) == true)
                .ToList();

            foreach (var p in toRemove)
            {
                operation.Parameters.Remove(p);
            }

            // ✅ Add the correct custom parameters
            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.filterBy",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Filter criteria as JSON. Example: {\"status\":\"1\",\"offsetMinutes\":\"0\"}",
                Schema = new OpenApiSchema
                {
                    Type = "string",
                    Example = new Microsoft.OpenApi.Any.OpenApiString("{\"status\":\"1\"}")
                }
            });

            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.sortBy",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Sort criteria as JSON. Example: {\"firstName\":\"ASC\"}",
                Schema = new OpenApiSchema
                {
                    Type = "string",
                    Example = new Microsoft.OpenApi.Any.OpenApiString("{\"firstName\":\"ASC\"}")
                }
            });

            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.pages.startRow",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Starting row index for pagination (default: 0)",
                Schema = new OpenApiSchema
                {
                    Type = "integer",
                    Format = "int32",
                    Default = new Microsoft.OpenApi.Any.OpenApiInteger(0)
                }
            });

            operation.Parameters.Add(new OpenApiParameter
            {
                Name = "datafilter.pages.resultsPerPage",
                In = ParameterLocation.Query,
                Required = false,
                Description = "Number of results per page (default: 100)",
                Schema = new OpenApiSchema
                {
                    Type = "integer",
                    Format = "int32",
                    Default = new Microsoft.OpenApi.Any.OpenApiInteger(100)
                }
            });
        }
    }
}
