services:
  unifiedloginlandingapi.api:
    image: ${DOCKER_REGISTRY-}/api:${TAG-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=LOCAL
    build:
      context: .
      dockerfile: UnifiedLogin.LandingAPI/Dockerfile
    ports:
      - "44335:8080"

  unifiedloginlandingapienterprise.api:
    image: ${DOCKER_REGISTRY-}/apienterprise:${TAG-latest}
    environment:
      - ASPNETCORE_ENVIRONMENT=LOCAL
    build:
      context: .
      dockerfile: UnifiedLogin.LandingAPIEnterprise/Dockerfile
    ports:
      - "44336:8080"

  UnifiedLogin.BatchProcessor:
    image: ${DOCKER_REGISTRY-}/unifiedlogin.batchprocessor:${TAG-latest}
    environment:
      - DOTNET_ENVIRONMENT=LOCAL
    build:
      context: .
      dockerfile: Services/UnifiedLogin.BatchProcessor/Dockerfile