{{{ include("templates/templates.inc.js") }}}

{{{ include("config/document-management.js") }}}
{{{ include("config/tabs.js") }}}


{{{ include("controllers/departments-grid.js") }}}
{{{ include("controllers/document-management-product-access.js") }}}
{{{ include("controllers/properties-grid.js") }}}
{{{ include("controllers/roles-grid.js") }}}

{{{ include("models/departments-grid.js") }}}
{{{ include("models/document-management-events.js") }}}
{{{ include("models/document-management.js") }}}
{{{ include("models/properties-grid.js") }}}
{{{ include("models/role-model.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/tabs.js") }}}

{{{ include("services/additional-data.js") }}}
{{{ include("services/roles-data.js") }}}

