
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-rights.js") }}}

{{{ include("models/spndmgmt-products-config.js") }}}
{{{ include("models/spndmgmt-products-menu.js") }}}
{{{ include("models/spndmgmt-rights-actions.js") }}}
{{{ include("models/spndmgmt-rights-config.js") }}}
{{{ include("models/spndmgmt-rights.js") }}}

{{{ include("directives/spndmgmt-actions.js") }}}

{{{ include("services/spndmgmt-products.js") }}}
{{{ include("services/spndmgmt-rights.js") }}}



