//  Note: Please do not alter the order
//  in which files are being included

{{{ include("breadcrumbs.js") }}}
{{{ include("core-lazy-load.js") }}}
{{{ include("environment.js") }}}
{{{ include("global-header-help-data.js") }}}
{{{ include("global-nav.js") }}}
{{{ include("lazy-load.js") }}}
{{{ include("location.js") }}}
{{{ include("oc-lazyload.js") }}}
{{{ include("resolve-modules.js") }}}
{{{ include("routes.js") }}}
{{{ include("ga.js") }}}
