
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/user-mgmt-rights.js") }}}



{{{ include("models/user-mgmt-rights-config.js") }}}
{{{ include("models/user-mgmt-rights-actions.js") }}}
{{{ include("models/user-mgmt-rights.js") }}}
{{{ include("models/user-mgmt-products-config.js") }}}


{{{ include("directives/user-mgmt-actions.js") }}}

{{{ include("services/user-mgmt-rights.js") }}}
{{{ //include("services/user-mgmt-products.js") }}}



