{{{ include("templates/templates.inc.js") }}}

{{{ include("config/tabs.js") }}}

{{{ include("controllers/messaging-groups-grid.js") }}}
{{{ include("controllers/notifications.js") }}}
{{{ include("controllers/properties-grid.js") }}}
{{{ include("controllers/resident-portals-product-access.js") }}}
{{{ include("controllers/roles-grid.js") }}}
{{{ include("controllers/roles-radio.js") }}}

{{{ include("filters/resident-portals-translator.js") }}}

{{{ include("models/messaging-groups-grid.js") }}}
{{{ include("models/properties-grid.js") }}}
{{{ include("models/resident-portals.js") }}}
{{{ include("models/roles-grid.js") }}}
{{{ include("models/role-model.js") }}}
{{{ include("models/tabs.js") }}}

{{{ include("services/messaging-groups-data.js") }}}
{{{ include("services/notifications-data.js") }}}
{{{ include("services/properties-data.js") }}}
{{{ include("services/roles-data.js") }}}
