
{{{ include("controllers/companies.js") }}}
{{{ include("controllers/company-bm-roles.js") }}}
{{{ include("controllers/company-property.js") }}}
{{{ include("controllers/company-roles.js") }}}
{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties-assigned-list-aside.js") }}}
{{{ include("controllers/properties-list-aside.js") }}}
{{{ include("controllers/property-groups.js") }}}
{{{ include("controllers/property-info-icon.js") }}}

{{{ include("directives/paproperty-action.js") }}}

{{{ include("models/company-config.js") }}}
{{{ include("models/company-grid-config-factory.js") }}}
{{{ include("models/company-property-config.js") }}}
{{{ include("models/company-roles.js") }}}
{{{ include("models/pa-sync-manager.js") }}}
{{{ include("models/performance-analytics.js") }}}
{{{ include("models/properties-config.js") }}}
{{{ include("models/properties-list-aside.js") }}}
{{{ include("models/property-assign-model.js") }}}
{{{ include("models/property-groups-config.js") }}}
{{{ include("models/property-list-grid.js") }}}
{{{ include("models/property-list.js") }}}

{{{ include("services/performance-analytics-assign-property-context.js") }}}
{{{ include("services/performance-analytics-assign-property.js") }}}
{{{ include("services/performance-analytics-tabs-data.js") }}}

{{{ include("templates/templates.inc.js") }}}
