// Templates

{{{ include("templates/templates.inc.js") }}}

// Config


// Controllers

{{{ include("controllers/product-access.js") }}}
{{{ include("controllers/properties.js") }}}
{{{ include("controllers/roles.js") }}}

// Models

{{{ include("models/properties-config.js") }}}
{{{ include("models/roles-config.js") }}}
{{{ include("models/tabs-menu.js") }}}
{{{ include("models/ilm-leadmanagement.js") }}}

