
{{{ include("templates/templates.inc.js") }}}

{{{ include("controllers/spndmgmt-delete-modal.js") }}}
{{{ include("controllers/spndmgmt-roles.js") }}}
{{{ include("controllers/spndmgmt-status-message.js") }}}


{{{ include("models/spndmgmt-assign-rights-products-data.js") }}}
{{{ include("models/spndmgmt-message-modal.js") }}}
{{{ include("models/spndmgmt-message.js") }}}
{{{ include("models/spndmgmt-roles-actions.js") }}}
{{{ include("models/spndmgmt-roles-config.js") }}}
{{{ include("models/spndmgmt-roles.js") }}}

{{{ include("directives/spndmgmt-actions.js") }}}

{{{ include("services/spndmgmt-assign-rights-products.js") }}}
{{{ include("services/spndmgmt-clone-role.js") }}}
{{{ include("services/spndmgmt-delete-role.js") }}}
{{{ include("services/spndmgmt-roles.js") }}}



