apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-login-coreapienterprisev2-config-$(environmentName)
  # namespace: unified-login
  labels:
    product: une
    module: unified-login-coreapienterprisev2
    location: gcp
    environment: $(environmentName)
data:
  ASPNETCORE_ENVIRONMENT: $(environmentName)

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-login-coreapiv2-config-$(environmentName)
  # namespace: unified-login
  labels:
    product: une
    module: unified-login-coreapiv2
    location: gcp
    environment: $(environmentName)
data:
  ASPNETCORE_ENVIRONMENT: $(environmentName)