{{{ include("config/product-templates-data.js") }}}
{{{ include("controllers/assign-product-access.js") }}}

{{{ include("models/assign-product-access.js") }}}
{{{ include("services/product-access-templates.js") }}}
{{{ include("services/ao-properties-data.js") }}}
{{{ include("services/ao-roles-data.js") }}}
{{{ include("services/ao-company-data.js") }}}
{{{ include("services/ao-property-group-data.js") }}}
{{{ include("services/ao-group-properties-data.js") }}}
{{{ include("services/ao-company-property-data.js") }}}
{{{ include("services/product-properties-data.js") }}}
{{{ include("services/product-roles-data.js") }}}
{{{ include("services/product-group-properties-data.js") }}}
{{{ include("services/product-property-groups-data.js") }}}
{{{ include("templates/templates.inc.js") }}}
{{{ include("filters/product-panel-text.js") }}}
