{{{ include("config/register-model.js") }}}

{{{ include("components/persona-tab.js") }}}

{{{ include("filters/persona-translator.js") }}}
{{{ include("filters/moment-date.js") }}}
{{{ include("filters/user-type-label.js") }}}

{{{ include("models/persona-form-config.js") }}}
{{{ include("models/persona-product-family.js") }}}
{{{ include("models/persona-product-item.js") }}}
{{{ include("models/persona-products.js") }}}
{{{ include("models/persona-type-config.js") }}}
{{{ include("models/products-panel-config.js") }}}
{{{ include("models/products-overall-data.js") }}}

{{{ include("services/persona-types.js") }}}

{{{ include("templates/templates.inc.js") }}}
