//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591


using System.Net;
using System.ServiceModel;
using System.Text;

namespace UnifiedLogin.SharedObjects.Product.OneSite;

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class OneSiteProductService : System.ServiceModel.ClientBase<OneSite.IOneSiteProductService>, OneSite.IOneSiteProductService
{
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    /// <summary>
    /// Custom constructor allowing caller to provide endpoint URL and credentials.
    /// </summary>
    /// <param name="endpointUrl">Service endpoint URL (e.g. https://.../productservice.asmx)</param>
    /// <param name="username">Service username</param>
    /// <param name="password">Service password</param>
    public OneSiteProductService(string endpointUrl, string username, string password)
        : base(GetBindingForEndpoint(EndpointConfiguration.ProductServicePortBinding), new EndpointAddress(endpointUrl))
    {
        this.Endpoint.Name = "CustomProductServiceEndpoint";
        this.ClientCredentials.UserName.UserName = username;
        this.ClientCredentials.UserName.Password = password;
        Url = endpointUrl; // maintain Url property state
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    /// <summary>
    /// Parameterless constructor for legacy calling code expecting a default instance.
    /// </summary>
    public OneSiteProductService()
        : base(GetBindingForEndpoint(EndpointConfiguration.ProductServicePortBinding), GetEndpointAddress(EndpointConfiguration.ProductServicePortBinding))
    {
        this.Endpoint.Name = EndpointConfiguration.ProductServicePortBinding.ToString();
        Url = this.Endpoint.Address.Uri.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    /// <summary>
    /// Backing storage for PreAuthenticate (not used by WCF BasicHttpBinding directly, kept for compatibility).
    /// </summary>
    private bool _preAuthenticate;

    /// <summary>
    /// Gets or sets the endpoint URL (maps to Endpoint.Address).
    /// </summary>
    public string Url
    {
        get => this.Endpoint.Address.Uri.ToString();
        set => this.Endpoint.Address = new EndpointAddress(value);
    }

    /// <summary>
    /// Gets or sets basic authentication credentials. Setting updates ClientCredentials.UserName.
    /// </summary>
    public NetworkCredential Credentials
    {
        get => new NetworkCredential(this.ClientCredentials?.UserName?.UserName, this.ClientCredentials?.UserName?.Password);
        set
        {
            if (value != null)
            {
                this.ClientCredentials.UserName.UserName = value.UserName;
                this.ClientCredentials.UserName.Password = value.Password;
            }
        }
    }

    /// <summary>
    /// Compatibility property (no operational impact for WCF BasicHttpBinding).
    /// </summary>
    public bool PreAuthenticate
    {
        get => _preAuthenticate;
        set => _preAuthenticate = value;
    }


    //public OneSiteProductService(EndpointConfiguration endpointConfiguration):
    //        base(OneSiteProductService.GetBindingForEndpoint(endpointConfiguration), OneSiteProductService.GetEndpointAddress(endpointConfiguration))
    //{
    //    this.Endpoint.Name = endpointConfiguration.ToString();
    //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    //}

    //public OneSiteProductService(EndpointConfiguration endpointConfiguration, string remoteAddress) :
    //        base(OneSiteProductService.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    //{
    //    this.Endpoint.Name = endpointConfiguration.ToString();
    //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    //}

    //public OneSiteProductService(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
    //        base(OneSiteProductService.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    //{
    //    this.Endpoint.Name = endpointConfiguration.ToString();
    //    ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    //}

    //public OneSiteProductService(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
    //        base(binding, remoteAddress)
    //{
    //}

    public bool ValidateUser(OneSite.NameValuePair[] User, string Password)
    {
        return base.Channel.ValidateUser(User, Password);
    }

    public System.Threading.Tasks.Task<bool> ValidateUserAsync(OneSite.NameValuePair[] User, string Password)
    {
        return base.Channel.ValidateUserAsync(User, Password);
    }

    public OneSite.UserExists CheckIfUserIDIsUsed(OneSite.NameValuePair[] uiArgs)
    {
        return base.Channel.CheckIfUserIDIsUsed(uiArgs);
    }

    public System.Threading.Tasks.Task<OneSite.UserExists> CheckIfUserIDIsUsedAsync(OneSite.NameValuePair[] uiArgs)
    {
        return base.Channel.CheckIfUserIDIsUsedAsync(uiArgs);
    }

    public OneSite.PMCInfo GetPMCUrl(int PMCID)
    {
        return base.Channel.GetPMCUrl(PMCID);
    }

    public System.Threading.Tasks.Task<OneSite.PMCInfo> GetPMCUrlAsync(int PMCID)
    {
        return base.Channel.GetPMCUrlAsync(PMCID);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OneSite.CreateSuperuserResponse OneSite.IOneSiteProductService.CreateSuperuser(OneSite.CreateSuperuserRequest request)
    {
        return base.Channel.CreateSuperuser(request);
    }

    public OneSite.NameValuePair[] CreateSuperuser(OneSite.NameValuePair[] User)
    {
        OneSite.CreateSuperuserRequest inValue = new OneSite.CreateSuperuserRequest();
        inValue.User = User;
        OneSite.CreateSuperuserResponse retVal = ((OneSite.IOneSiteProductService)(this)).CreateSuperuser(inValue);
        return retVal.UserInfo;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.CreateSuperuserResponse> OneSite.IOneSiteProductService.CreateSuperuserAsync(OneSite.CreateSuperuserRequest request)
    {
        return base.Channel.CreateSuperuserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.CreateSuperuserResponse> CreateSuperuserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.CreateSuperuserRequest inValue = new OneSite.CreateSuperuserRequest();
        inValue.User = User;
        return ((OneSite.IOneSiteProductService)(this)).CreateSuperuserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OneSite.CreateUserResponse OneSite.IOneSiteProductService.CreateUser(OneSite.CreateUserRequest request)
    {
        return base.Channel.CreateUser(request);
    }

    public OneSite.NameValuePair[] CreateUser(OneSite.NameValuePair[] User)
    {
        OneSite.CreateUserRequest inValue = new OneSite.CreateUserRequest();
        inValue.User = User;
        OneSite.CreateUserResponse retVal = ((OneSite.IOneSiteProductService)(this)).CreateUser(inValue);
        return retVal.UserInfo;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.CreateUserResponse> OneSite.IOneSiteProductService.CreateUserAsync(OneSite.CreateUserRequest request)
    {
        return base.Channel.CreateUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.CreateUserResponse> CreateUserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.CreateUserRequest inValue = new OneSite.CreateUserRequest();
        inValue.User = User;
        return ((OneSite.IOneSiteProductService)(this)).CreateUserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OneSite.UpdateSuperuserResponse OneSite.IOneSiteProductService.UpdateSuperuser(OneSite.UpdateSuperuserRequest request)
    {
        return base.Channel.UpdateSuperuser(request);
    }

    public OneSite.NameValuePair[] UpdateSuperuser(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateSuperuserRequest inValue = new OneSite.UpdateSuperuserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        OneSite.UpdateSuperuserResponse retVal = ((OneSite.IOneSiteProductService)(this)).UpdateSuperuser(inValue);
        return retVal.UserInfo;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.UpdateSuperuserResponse> OneSite.IOneSiteProductService.UpdateSuperuserAsync(OneSite.UpdateSuperuserRequest request)
    {
        return base.Channel.UpdateSuperuserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.UpdateSuperuserResponse> UpdateSuperuserAsync(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateSuperuserRequest inValue = new OneSite.UpdateSuperuserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        return ((OneSite.IOneSiteProductService)(this)).UpdateSuperuserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OneSite.UpdateUserResponse OneSite.IOneSiteProductService.UpdateUser(OneSite.UpdateUserRequest request)
    {
        return base.Channel.UpdateUser(request);
    }

    public OneSite.NameValuePair[] UpdateUser(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateUserRequest inValue = new OneSite.UpdateUserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        OneSite.UpdateUserResponse retVal = ((OneSite.IOneSiteProductService)(this)).UpdateUser(inValue);
        return retVal.UserInfo;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.UpdateUserResponse> OneSite.IOneSiteProductService.UpdateUserAsync(OneSite.UpdateUserRequest request)
    {
        return base.Channel.UpdateUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.UpdateUserResponse> UpdateUserAsync(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateUserRequest inValue = new OneSite.UpdateUserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        return ((OneSite.IOneSiteProductService)(this)).UpdateUserAsync(inValue);
    }

    public OneSite.AssignStatus AssignPropertiesToUser(string SystemIdentifier, string SelectedPropertyIds)
    {
        return base.Channel.AssignPropertiesToUser(SystemIdentifier, SelectedPropertyIds);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> AssignPropertiesToUserAsync(string SystemIdentifier, string SelectedPropertyIds)
    {
        return base.Channel.AssignPropertiesToUserAsync(SystemIdentifier, SelectedPropertyIds);
    }

    public OneSite.AssignStatus RemovePropertiesFromUser(string SystemIdentifier, string PropertyIdsToRemove)
    {
        return base.Channel.RemovePropertiesFromUser(SystemIdentifier, PropertyIdsToRemove);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> RemovePropertiesFromUserAsync(string SystemIdentifier, string PropertyIdsToRemove)
    {
        return base.Channel.RemovePropertiesFromUserAsync(SystemIdentifier, PropertyIdsToRemove);
    }

    public OneSite.AssignStatus AssignRolesToUser(string SystemIdentifier, string SelectedRoleIds)
    {
        return base.Channel.AssignRolesToUser(SystemIdentifier, SelectedRoleIds);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> AssignRolesToUserAsync(string SystemIdentifier, string SelectedRoleIds)
    {
        return base.Channel.AssignRolesToUserAsync(SystemIdentifier, SelectedRoleIds);
    }

    public OneSite.AssignStatus RemoveRolesFromUser(string SystemIdentifier, string RoleIdsToRemove)
    {
        return base.Channel.RemoveRolesFromUser(SystemIdentifier, RoleIdsToRemove);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> RemoveRolesFromUserAsync(string SystemIdentifier, string RoleIdsToRemove)
    {
        return base.Channel.RemoveRolesFromUserAsync(SystemIdentifier, RoleIdsToRemove);
    }

    public void EnableUser(string SystemIdentifier)
    {
        base.Channel.EnableUser(SystemIdentifier);
    }

    public System.Threading.Tasks.Task EnableUserAsync(string SystemIdentifier)
    {
        return base.Channel.EnableUserAsync(SystemIdentifier);
    }

    public void ResetVerificationCode(string SystemIdentifier)
    {
        base.Channel.ResetVerificationCode(SystemIdentifier);
    }

    public System.Threading.Tasks.Task ResetVerificationCodeAsync(string SystemIdentifier)
    {
        return base.Channel.ResetVerificationCodeAsync(SystemIdentifier);
    }

    public void DisableUser(string SystemIdentifier)
    {
        base.Channel.DisableUser(SystemIdentifier);
    }

    public System.Threading.Tasks.Task DisableUserAsync(string SystemIdentifier)
    {
        return base.Channel.DisableUserAsync(SystemIdentifier);
    }

    public OneSite.PropertyList GetAllProperties(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllProperties(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetAllPropertiesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllPropertiesAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public OneSite.PropertyList GetDefaultProperties(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultProperties(uiArgs, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetDefaultPropertiesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultPropertiesAsync(uiArgs, filterSortParameters);
    }

    public OneSite.PropertyList GetUserProperties(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserProperties(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetUserPropertiesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserPropertiesAsync(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public OneSite.UserList GetUsersForProperty(string SystemIdentifier, int PropertyID, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForProperty(SystemIdentifier, PropertyID, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.UserList> GetUsersForPropertyAsync(string SystemIdentifier, int PropertyID, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForPropertyAsync(SystemIdentifier, PropertyID, AssignedOnly, filterSortParameters);
    }

    public OneSite.RoleList GetAllRoles(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllRoles(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetAllRolesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllRolesAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public OneSite.RoleList GetDefaultRoles(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultRoles(uiArgs, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetDefaultRolesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultRolesAsync(uiArgs, filterSortParameters);
    }

    public OneSite.RoleList GetUserRoles(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserRoles(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetUserRolesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserRolesAsync(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public OneSite.UserList GetUsersForRole(string SystemIdentifier, int RoleId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForRole(SystemIdentifier, RoleId, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.UserList> GetUsersForRoleAsync(string SystemIdentifier, int RoleId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForRoleAsync(SystemIdentifier, RoleId, AssignedOnly, filterSortParameters);
    }

    public void DeleteUser(string SystemIdentifier, string DeleteUserSystemIdentifier)
    {
        base.Channel.DeleteUser(SystemIdentifier, DeleteUserSystemIdentifier);
    }

    public System.Threading.Tasks.Task DeleteUserAsync(string SystemIdentifier, string DeleteUserSystemIdentifier)
    {
        return base.Channel.DeleteUserAsync(SystemIdentifier, DeleteUserSystemIdentifier);
    }

    public void ClaimUser(string SystemIdentifier, bool IsLinked)
    {
        base.Channel.ClaimUser(SystemIdentifier, IsLinked);
    }

    public System.Threading.Tasks.Task ClaimUserAsync(string SystemIdentifier, bool IsLinked)
    {
        return base.Channel.ClaimUserAsync(SystemIdentifier, IsLinked);
    }

    public void ClaimUserUL(string SystemIdentifier, bool IsULLinked)
    {
        base.Channel.ClaimUserUL(SystemIdentifier, IsULLinked);
    }

    public System.Threading.Tasks.Task ClaimUserULAsync(string SystemIdentifier, bool IsULLinked)
    {
        return base.Channel.ClaimUserULAsync(SystemIdentifier, IsULLinked);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    OneSite.GetUserResponse OneSite.IOneSiteProductService.GetUser(OneSite.GetUserRequest request)
    {
        return base.Channel.GetUser(request);
    }

    public OneSite.NameValuePair[] GetUser(OneSite.NameValuePair[] User)
    {
        OneSite.GetUserRequest inValue = new OneSite.GetUserRequest();
        inValue.User = User;
        OneSite.GetUserResponse retVal = ((OneSite.IOneSiteProductService)(this)).GetUser(inValue);
        return retVal.UserInfo;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.GetUserResponse> OneSite.IOneSiteProductService.GetUserAsync(OneSite.GetUserRequest request)
    {
        return base.Channel.GetUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.GetUserResponse> GetUserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.GetUserRequest inValue = new OneSite.GetUserRequest();
        inValue.User = User;
        return ((OneSite.IOneSiteProductService)(this)).GetUserAsync(inValue);
    }

    public OneSite.RightCenter GetRightsCentersList(OneSite.NameValuePair[] uiArgs, string SystemIdentifier)
    {
        return base.Channel.GetRightsCentersList(uiArgs, SystemIdentifier);
    }

    public System.Threading.Tasks.Task<OneSite.RightCenter> GetRightsCentersListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier)
    {
        return base.Channel.GetRightsCentersListAsync(uiArgs, SystemIdentifier);
    }

    public OneSite.RightList GetRightsList(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRightsList(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RightList> GetRightsListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRightsListAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public OneSite.AssignStatus ModifyRightToRoles(string SystemIdentifier, int RightId, string SelectedRoleIds, bool AssignRight)
    {
        return base.Channel.ModifyRightToRoles(SystemIdentifier, RightId, SelectedRoleIds, AssignRight);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRightToRolesAsync(string SystemIdentifier, int RightId, string SelectedRoleIds, bool AssignRight)
    {
        return base.Channel.ModifyRightToRolesAsync(SystemIdentifier, RightId, SelectedRoleIds, AssignRight);
    }

    public OneSite.AssignStatus ModifyRoleToRights(string SystemIdentifier, int RoleId, string RightIdsToAdd, string RightIdsToRemove)
    {
        return base.Channel.ModifyRoleToRights(SystemIdentifier, RoleId, RightIdsToAdd, RightIdsToRemove);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRoleToRightsAsync(string SystemIdentifier, int RoleId, string RightIdsToAdd, string RightIdsToRemove)
    {
        return base.Channel.ModifyRoleToRightsAsync(SystemIdentifier, RoleId, RightIdsToAdd, RightIdsToRemove);
    }

    public OneSite.RoleList GetRolesForRight(OneSite.NameValuePair[] uiArgs, int RightId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRolesForRight(uiArgs, RightId, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetRolesForRightAsync(OneSite.NameValuePair[] uiArgs, int RightId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRolesForRightAsync(uiArgs, RightId, AssignedOnly, filterSortParameters);
    }

    public OneSite.RoleList AddUpdateRole(string SystemIdentifier, string RoleId, string RoleName, string InheritRoleID)
    {
        return base.Channel.AddUpdateRole(SystemIdentifier, RoleId, RoleName, InheritRoleID);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> AddUpdateRoleAsync(string SystemIdentifier, string RoleId, string RoleName, string InheritRoleID)
    {
        return base.Channel.AddUpdateRoleAsync(SystemIdentifier, RoleId, RoleName, InheritRoleID);
    }

    public void DeleteRole(string SystemIdentifier, int RoleID)
    {
        base.Channel.DeleteRole(SystemIdentifier, RoleID);
    }

    public System.Threading.Tasks.Task DeleteRoleAsync(string SystemIdentifier, int RoleID)
    {
        return base.Channel.DeleteRoleAsync(SystemIdentifier, RoleID);
    }

    public bool GetUserInLeasingAgentList(string SystemIdentifier, int SiteID)
    {
        return base.Channel.GetUserInLeasingAgentList(SystemIdentifier, SiteID);
    }

    public System.Threading.Tasks.Task<bool> GetUserInLeasingAgentListAsync(string SystemIdentifier, int SiteID)
    {
        return base.Channel.GetUserInLeasingAgentListAsync(SystemIdentifier, SiteID);
    }

    public bool authenticate(string username, string password, string additionalInfo)
    {
        return base.Channel.authenticate(username, password, additionalInfo);
    }

    public System.Threading.Tasks.Task<bool> authenticateAsync(string username, string password, string additionalInfo)
    {
        return base.Channel.authenticateAsync(username, password, additionalInfo);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding))
        {
            return new System.ServiceModel.EndpointAddress("https://sat.realpage.com/logonsvc/productservice.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    public enum EndpointConfiguration
    {
        ProductServicePortBinding
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class NameValuePair : object, System.ComponentModel.INotifyPropertyChanged
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string rightIDField;

    private string rightDescriptionField;

    private string centerNameField;

    private bool assignedField;

    private int rolesAssignedField;

    private string usageDescriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string RightID
    {
        get
        {
            return this.rightIDField;
        }
        set
        {
            this.rightIDField = value;
            this.RaisePropertyChanged("RightID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string RightDescription
    {
        get
        {
            return this.rightDescriptionField;
        }
        set
        {
            this.rightDescriptionField = value;
            this.RaisePropertyChanged("RightDescription");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CenterName
    {
        get
        {
            return this.centerNameField;
        }
        set
        {
            this.centerNameField = value;
            this.RaisePropertyChanged("CenterName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool Assigned
    {
        get
        {
            return this.assignedField;
        }
        set
        {
            this.assignedField = value;
            this.RaisePropertyChanged("Assigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public int RolesAssigned
    {
        get
        {
            return this.rolesAssignedField;
        }
        set
        {
            this.rolesAssignedField = value;
            this.RaisePropertyChanged("RolesAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string UsageDescription
    {
        get
        {
            return this.usageDescriptionField;
        }
        set
        {
            this.usageDescriptionField = value;
            this.RaisePropertyChanged("UsageDescription");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private RightType[] rightField;

    private int totalRightsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public RightType[] Right
    {
        get
        {
            return this.rightField;
        }
        set
        {
            this.rightField = value;
            this.RaisePropertyChanged("Right");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalRights
    {
        get
        {
            return this.totalRightsField;
        }
        set
        {
            this.totalRightsField = value;
            this.RaisePropertyChanged("TotalRights");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightCenter : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private string[] rightCentersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public string[] RightCenters
    {
        get
        {
            return this.rightCentersField;
        }
        set
        {
            this.rightCentersField = value;
            this.RaisePropertyChanged("RightCenters");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RoleType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string roleIDField;

    private string roleNameField;

    private string rightsAssignedField;

    private bool isInternalField;

    private string roletypeField;

    private bool isAssignedField;

    private string inheritedRoleNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string RoleID
    {
        get
        {
            return this.roleIDField;
        }
        set
        {
            this.roleIDField = value;
            this.RaisePropertyChanged("RoleID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string RoleName
    {
        get
        {
            return this.roleNameField;
        }
        set
        {
            this.roleNameField = value;
            this.RaisePropertyChanged("RoleName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string RightsAssigned
    {
        get
        {
            return this.rightsAssignedField;
        }
        set
        {
            this.rightsAssignedField = value;
            this.RaisePropertyChanged("RightsAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool IsInternal
    {
        get
        {
            return this.isInternalField;
        }
        set
        {
            this.isInternalField = value;
            this.RaisePropertyChanged("IsInternal");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Roletype
    {
        get
        {
            return this.roletypeField;
        }
        set
        {
            this.roletypeField = value;
            this.RaisePropertyChanged("Roletype");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public bool IsAssigned
    {
        get
        {
            return this.isAssignedField;
        }
        set
        {
            this.isAssignedField = value;
            this.RaisePropertyChanged("IsAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string InheritedRoleName
    {
        get
        {
            return this.inheritedRoleNameField;
        }
        set
        {
            this.inheritedRoleNameField = value;
            this.RaisePropertyChanged("InheritedRoleName");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RoleList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private RoleType[] roleField;

    private int totalRolesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public RoleType[] Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
            this.RaisePropertyChanged("Role");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalRoles
    {
        get
        {
            return this.totalRolesField;
        }
        set
        {
            this.totalRolesField = value;
            this.RaisePropertyChanged("TotalRoles");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserType : object, System.ComponentModel.INotifyPropertyChanged
{

    private int userIdField;

    private string userLoginField;

    private string userNameField;

    private bool assignedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string UserLogin
    {
        get
        {
            return this.userLoginField;
        }
        set
        {
            this.userLoginField = value;
            this.RaisePropertyChanged("UserLogin");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
            this.RaisePropertyChanged("UserName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool Assigned
    {
        get
        {
            return this.assignedField;
        }
        set
        {
            this.assignedField = value;
            this.RaisePropertyChanged("Assigned");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private UserType[] userField;

    private int totalUsersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public UserType[] User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
            this.RaisePropertyChanged("User");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalUsers
    {
        get
        {
            return this.totalUsersField;
        }
        set
        {
            this.totalUsersField = value;
            this.RaisePropertyChanged("TotalUsers");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PropertyType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string propertyIDField;

    private string propertyNameField;

    private string siteAddressField;

    private string siteCityNameField;

    private string siteStateField;

    private string siteZipField;

    private string sitePhoneField;

    private bool isAssignedToUserField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string PropertyID
    {
        get
        {
            return this.propertyIDField;
        }
        set
        {
            this.propertyIDField = value;
            this.RaisePropertyChanged("PropertyID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string PropertyName
    {
        get
        {
            return this.propertyNameField;
        }
        set
        {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string SiteAddress
    {
        get
        {
            return this.siteAddressField;
        }
        set
        {
            this.siteAddressField = value;
            this.RaisePropertyChanged("SiteAddress");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string SiteCityName
    {
        get
        {
            return this.siteCityNameField;
        }
        set
        {
            this.siteCityNameField = value;
            this.RaisePropertyChanged("SiteCityName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SiteState
    {
        get
        {
            return this.siteStateField;
        }
        set
        {
            this.siteStateField = value;
            this.RaisePropertyChanged("SiteState");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string SiteZip
    {
        get
        {
            return this.siteZipField;
        }
        set
        {
            this.siteZipField = value;
            this.RaisePropertyChanged("SiteZip");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string SitePhone
    {
        get
        {
            return this.sitePhoneField;
        }
        set
        {
            this.sitePhoneField = value;
            this.RaisePropertyChanged("SitePhone");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public bool IsAssignedToUser
    {
        get
        {
            return this.isAssignedToUserField;
        }
        set
        {
            this.isAssignedToUserField = value;
            this.RaisePropertyChanged("IsAssignedToUser");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PropertyList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private PropertyType[] propertyField;

    private int totalPropertiesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public PropertyType[] Property
    {
        get
        {
            return this.propertyField;
        }
        set
        {
            this.propertyField = value;
            this.RaisePropertyChanged("Property");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalProperties
    {
        get
        {
            return this.totalPropertiesField;
        }
        set
        {
            this.totalPropertiesField = value;
            this.RaisePropertyChanged("TotalProperties");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class SortCondition : object, System.ComponentModel.INotifyPropertyChanged
{

    private string columnNameField;

    private string sortDirectionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ColumnName
    {
        get
        {
            return this.columnNameField;
        }
        set
        {
            this.columnNameField = value;
            this.RaisePropertyChanged("ColumnName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string SortDirection
    {
        get
        {
            return this.sortDirectionField;
        }
        set
        {
            this.sortDirectionField = value;
            this.RaisePropertyChanged("SortDirection");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class FilterCondition : object, System.ComponentModel.INotifyPropertyChanged
{

    private string propertyNameField;

    private string searchValueField;

    private string operatorField;

    private string querySuffixField;

    private string searchTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string PropertyName
    {
        get
        {
            return this.propertyNameField;
        }
        set
        {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string SearchValue
    {
        get
        {
            return this.searchValueField;
        }
        set
        {
            this.searchValueField = value;
            this.RaisePropertyChanged("SearchValue");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Operator
    {
        get
        {
            return this.operatorField;
        }
        set
        {
            this.operatorField = value;
            this.RaisePropertyChanged("Operator");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string QuerySuffix
    {
        get
        {
            return this.querySuffixField;
        }
        set
        {
            this.querySuffixField = value;
            this.RaisePropertyChanged("QuerySuffix");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SearchType
    {
        get
        {
            return this.searchTypeField;
        }
        set
        {
            this.searchTypeField = value;
            this.RaisePropertyChanged("SearchType");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class FilterSortParameters : object, System.ComponentModel.INotifyPropertyChanged
{

    private int startPositionField;

    private int pageLengthField;

    private FilterCondition[] filterConditionListField;

    private SortCondition sortConditionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int StartPosition
    {
        get
        {
            return this.startPositionField;
        }
        set
        {
            this.startPositionField = value;
            this.RaisePropertyChanged("StartPosition");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int PageLength
    {
        get
        {
            return this.pageLengthField;
        }
        set
        {
            this.pageLengthField = value;
            this.RaisePropertyChanged("PageLength");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
    public FilterCondition[] FilterConditionList
    {
        get
        {
            return this.filterConditionListField;
        }
        set
        {
            this.filterConditionListField = value;
            this.RaisePropertyChanged("FilterConditionList");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public SortCondition SortCondition
    {
        get
        {
            return this.sortConditionField;
        }
        set
        {
            this.sortConditionField = value;
            this.RaisePropertyChanged("SortCondition");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class AssignStatus : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorMessageField;

    private bool resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
            this.RaisePropertyChanged("ErrorMessage");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
            this.RaisePropertyChanged("Result");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PMCInfo : object, System.ComponentModel.INotifyPropertyChanged
{

    private string dBMachineField;

    private string pMCURLField;

    private int idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string DBMachine
    {
        get
        {
            return this.dBMachineField;
        }
        set
        {
            this.dBMachineField = value;
            this.RaisePropertyChanged("DBMachine");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string PMCURL
    {
        get
        {
            return this.pMCURLField;
        }
        set
        {
            this.pMCURLField = value;
            this.RaisePropertyChanged("PMCURL");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserExists : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorMessageField;

    private bool resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
            this.RaisePropertyChanged("ErrorMessage");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
            this.RaisePropertyChanged("Result");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateSuperuser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateSuperuserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public CreateSuperuserRequest()
    {
    }

    public CreateSuperuserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateSuperuserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateSuperuserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public CreateSuperuserResponse()
    {
    }

    public CreateSuperuserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public CreateUserRequest()
    {
    }

    public CreateUserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public CreateUserResponse()
    {
    }

    public CreateUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateSuperuser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateSuperuserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public string SystemIdentifier;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 1)]
    public OneSite.NameValuePair[] User;

    public UpdateSuperuserRequest()
    {
    }

    public UpdateSuperuserRequest(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        this.SystemIdentifier = SystemIdentifier;
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateSuperuserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateSuperuserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public UpdateSuperuserResponse()
    {
    }

    public UpdateSuperuserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public string SystemIdentifier;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 1)]
    public OneSite.NameValuePair[] User;

    public UpdateUserRequest()
    {
    }

    public UpdateUserRequest(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        this.SystemIdentifier = SystemIdentifier;
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public UpdateUserResponse()
    {
    }

    public UpdateUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class GetUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public GetUserRequest()
    {
    }

    public GetUserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class GetUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public GetUserResponse()
    {
    }

    public GetUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

//[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
//public interface ProductServicePortBindingChannel : OneSite.IOneSiteProductService, System.ServiceModel.IClientChannel
//{
//}