//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591


using System.ServiceModel;
using System.Text;

namespace UnifiedLogin.SharedObjects.Product.OneSite;

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://realpage.com/webservices", ConfigurationName = "OneSite.ProductServicePortBinding")]
public interface ProductServicePortBinding
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/ValidateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
    System.Threading.Tasks.Task<bool> ValidateUserAsync(OneSite.NameValuePair[] User, string Password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/CheckIfUserIDIsUsed", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "UserExists")]
    System.Threading.Tasks.Task<OneSite.UserExists> CheckIfUserIDIsUsedAsync(OneSite.NameValuePair[] uiArgs);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetPMCUrl", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "PMCInfo")]
    System.Threading.Tasks.Task<OneSite.PMCInfo> GetPMCUrlAsync(int PMCID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/CreateSuperuser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<OneSite.CreateSuperuserResponse> CreateSuperuserAsync(OneSite.CreateSuperuserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/CreateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<OneSite.CreateUserResponse> CreateUserAsync(OneSite.CreateUserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/UpdateSuperuser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<OneSite.UpdateSuperuserResponse> UpdateSuperuserAsync(OneSite.UpdateSuperuserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/UpdateUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<OneSite.UpdateUserResponse> UpdateUserAsync(OneSite.UpdateUserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/AssignPropertiesToUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> AssignPropertiesToUserAsync(string SystemIdentifier, string SelectedPropertyIds);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/RemovePropertiesFromUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> RemovePropertiesFromUserAsync(string SystemIdentifier, string PropertyIdsToRemove);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/AssignRolesToUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> AssignRolesToUserAsync(string SystemIdentifier, string SelectedRoleIds);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/RemoveRolesFromUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> RemoveRolesFromUserAsync(string SystemIdentifier, string RoleIdsToRemove);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/EnableUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task EnableUserAsync(string SystemIdentifier);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/ResetVerificationCode", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task ResetVerificationCodeAsync(string SystemIdentifier);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/DisableUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task DisableUserAsync(string SystemIdentifier);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetAllPropertiesWithSortFilters", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "PropertyList")]
    System.Threading.Tasks.Task<OneSite.PropertyList> GetAllPropertiesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetDefaultProperties", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "PropertyList")]
    System.Threading.Tasks.Task<OneSite.PropertyList> GetDefaultPropertiesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUserProperties", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "PropertyList")]
    System.Threading.Tasks.Task<OneSite.PropertyList> GetUserPropertiesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUsersForProperty", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "UserList")]
    System.Threading.Tasks.Task<OneSite.UserList> GetUsersForPropertyAsync(string SystemIdentifier, int PropertyID, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetAllRoles", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RoleList")]
    System.Threading.Tasks.Task<OneSite.RoleList> GetAllRolesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetDefaultRoles", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RoleList")]
    System.Threading.Tasks.Task<OneSite.RoleList> GetDefaultRolesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUserRoles", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RoleList")]
    System.Threading.Tasks.Task<OneSite.RoleList> GetUserRolesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUsersForRole", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "UserList")]
    System.Threading.Tasks.Task<OneSite.UserList> GetUsersForRoleAsync(string SystemIdentifier, int RoleId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/DeleteUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task DeleteUserAsync(string SystemIdentifier, string DeleteUserSystemIdentifier);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/ClaimUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task ClaimUserAsync(string SystemIdentifier, bool IsLinked);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/ClaimUserUL", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task ClaimUserULAsync(string SystemIdentifier, bool IsULLinked);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUser", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task<OneSite.GetUserResponse> GetUserAsync(OneSite.GetUserRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetRightsCentersList", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RightCenter")]
    System.Threading.Tasks.Task<OneSite.RightCenter> GetRightsCentersListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetRightsList", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RightList")]
    System.Threading.Tasks.Task<OneSite.RightList> GetRightsListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/AssignRightToRoles", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRightToRolesAsync(string SystemIdentifier, int RightId, string SelectedRoleIds, bool AssignRight);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/ModifyRoleToRights", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "AssignStatus")]
    System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRoleToRightsAsync(string SystemIdentifier, int RoleId, string RightIdsToAdd, string RightIdsToRemove);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetRolesForRight", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RoleList")]
    System.Threading.Tasks.Task<OneSite.RoleList> GetRolesForRightAsync(OneSite.NameValuePair[] uiArgs, int RightId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/AddUpdateRole", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "RoleList")]
    System.Threading.Tasks.Task<OneSite.RoleList> AddUpdateRoleAsync(string SystemIdentifier, string RoleId, string RoleName, string InheritRoleID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/DeleteRole", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    System.Threading.Tasks.Task DeleteRoleAsync(string SystemIdentifier, int RoleID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/GetUserInLeasingAgentList", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
    System.Threading.Tasks.Task<bool> GetUserInLeasingAgentListAsync(string SystemIdentifier, int SiteID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://realpage.com/webservices/authenticate", ReplyAction = "*")]
    [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
    [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
    System.Threading.Tasks.Task<bool> authenticateAsync(string username, string password, string additionalInfo);
}

/// <summary>
/// Facade over ProductServicePortBindingClient exposing async methods.
/// Now uses the generated WCF client's true async methods directly (no Task.Run wrapping).
/// </summary>
public class OneSiteProductService : IOneSiteProductService
{
    private readonly ProductServicePortBindingClient _client;
    private readonly string _username; // basic auth username
    private readonly string _password; // basic auth password

    public OneSiteProductService()
    {
        // In a real application inject these (e.g. via IOptions or secrets)
        _username = Encoding.UTF8.GetString(Convert.FromBase64String("cmVhbHBhZ2Vzc28="));
        _password = Encoding.UTF8.GetString(Convert.FromBase64String("Y2FwZTQ3T1BFczk2RXdFcnM="));

        _client = new ProductServicePortBindingClient(ProductServicePortBindingClient.EndpointConfiguration.ProductServicePortBinding);

        // Ensure transport client credential type is Basic so credentials are sent.
        if (_client.Endpoint.Binding is BasicHttpBinding basicBinding)
        {
            basicBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.Basic;
        }

        // Set HTTP Basic credentials.
        _client.ClientCredentials.UserName.UserName = _username;
        _client.ClientCredentials.UserName.Password = _password;
    }

    public Task<bool> ValidateUserAsync(NameValuePair[] user, string password) => _client.ValidateUserAsync(user, password);
    public Task<UserExists> CheckIfUserIDIsUsedAsync(NameValuePair[] uiArgs) => _client.CheckIfUserIDIsUsedAsync(uiArgs);
    public Task<PMCInfo> GetPMCUrlAsync(int pmcId) => _client.GetPMCUrlAsync(pmcId);
    public Task<CreateSuperuserResponse> CreateSuperuserAsync(NameValuePair[] user) => _client.CreateSuperuserAsync(user);
    public Task<CreateUserResponse> CreateUserAsync(NameValuePair[] user) => _client.CreateUserAsync(user);
    public Task<UpdateSuperuserResponse> UpdateSuperuserAsync(string systemIdentifier, NameValuePair[] user) => _client.UpdateSuperuserAsync(systemIdentifier, user);
    public Task<UpdateUserResponse> UpdateUserAsync(string systemIdentifier, NameValuePair[] user) => _client.UpdateUserAsync(systemIdentifier, user);
    public Task<AssignStatus> AssignPropertiesToUserAsync(string systemIdentifier, string selectedPropertyIds) => _client.AssignPropertiesToUserAsync(systemIdentifier, selectedPropertyIds);
    public Task<AssignStatus> RemovePropertiesFromUserAsync(string systemIdentifier, string propertyIdsToRemove) => _client.RemovePropertiesFromUserAsync(systemIdentifier, propertyIdsToRemove);
    public Task<AssignStatus> AssignRolesToUserAsync(string systemIdentifier, string selectedRoleIds) => _client.AssignRolesToUserAsync(systemIdentifier, selectedRoleIds);
    public Task<AssignStatus> RemoveRolesFromUserAsync(string systemIdentifier, string roleIdsToRemove) => _client.RemoveRolesFromUserAsync(systemIdentifier, roleIdsToRemove);
    public Task EnableUserAsync(string systemIdentifier) => _client.EnableUserAsync(systemIdentifier);
    public Task ResetVerificationCodeAsync(string systemIdentifier) => _client.ResetVerificationCodeAsync(systemIdentifier);
    public Task DisableUserAsync(string systemIdentifier) => _client.DisableUserAsync(systemIdentifier);
    public Task<PropertyList> GetAllPropertiesAsync(NameValuePair[] uiArgs, string systemIdentifier, FilterSortParameters filterSortParameters) => _client.GetAllPropertiesAsync(uiArgs, systemIdentifier, filterSortParameters);
    public Task<PropertyList> GetDefaultPropertiesAsync(NameValuePair[] uiArgs, FilterSortParameters filterSortParameters) => _client.GetDefaultPropertiesAsync(uiArgs, filterSortParameters);
    public Task<PropertyList> GetUserPropertiesAsync(string systemIdentifier, bool assignedOnly, FilterSortParameters filterSortParameters) => _client.GetUserPropertiesAsync(systemIdentifier, assignedOnly, filterSortParameters);
    public Task<UserList> GetUsersForPropertyAsync(string systemIdentifier, int propertyId, bool assignedOnly, FilterSortParameters filterSortParameters) => _client.GetUsersForPropertyAsync(systemIdentifier, propertyId, assignedOnly, filterSortParameters);
    public Task<RoleList> GetAllRolesAsync(NameValuePair[] uiArgs, string systemIdentifier, FilterSortParameters filterSortParameters) => _client.GetAllRolesAsync(uiArgs, systemIdentifier, filterSortParameters);
    public Task<RoleList> GetDefaultRolesAsync(NameValuePair[] uiArgs, FilterSortParameters filterSortParameters) => _client.GetDefaultRolesAsync(uiArgs, filterSortParameters);
    public Task<RoleList> GetUserRolesAsync(string systemIdentifier, bool assignedOnly, FilterSortParameters filterSortParameters) => _client.GetUserRolesAsync(systemIdentifier, assignedOnly, filterSortParameters);
    public Task<UserList> GetUsersForRoleAsync(string systemIdentifier, int roleId, bool assignedOnly, FilterSortParameters filterSortParameters) => _client.GetUsersForRoleAsync(systemIdentifier, roleId, assignedOnly, filterSortParameters);
    public Task DeleteUserAsync(string systemIdentifier, string deleteUserSystemIdentifier) => _client.DeleteUserAsync(systemIdentifier, deleteUserSystemIdentifier);
    public Task ClaimUserAsync(string systemIdentifier, bool isLinked) => _client.ClaimUserAsync(systemIdentifier, isLinked);
    public Task ClaimUserULAsync(string systemIdentifier, bool isUlLinked) => _client.ClaimUserULAsync(systemIdentifier, isUlLinked);
    public Task<GetUserResponse> GetUserAsync(NameValuePair[] user) => _client.GetUserAsync(user);
    public Task<RightCenter> GetRightsCentersListAsync(NameValuePair[] uiArgs, string systemIdentifier) => _client.GetRightsCentersListAsync(uiArgs, systemIdentifier);
    public Task<RightList> GetRightsListAsync(NameValuePair[] uiArgs, string systemIdentifier, FilterSortParameters filterSortParameters) => _client.GetRightsListAsync(uiArgs, systemIdentifier, filterSortParameters);
    public Task<AssignStatus> ModifyRightToRolesAsync(string systemIdentifier, int rightId, string selectedRoleIds, bool assignRight) => _client.ModifyRightToRolesAsync(systemIdentifier, rightId, selectedRoleIds, assignRight);
    public Task<AssignStatus> ModifyRoleToRightsAsync(string systemIdentifier, int roleId, string rightIdsToAdd, string rightIdsToRemove) => _client.ModifyRoleToRightsAsync(systemIdentifier, roleId, rightIdsToAdd, rightIdsToRemove);
    public Task<RoleList> GetRolesForRightAsync(NameValuePair[] uiArgs, int rightId, bool assignedOnly, FilterSortParameters filterSortParameters) => _client.GetRolesForRightAsync(uiArgs, rightId, assignedOnly, filterSortParameters);
    public Task<RoleList> AddUpdateRoleAsync(string systemIdentifier, string roleId, string roleName, string inheritRoleId) => _client.AddUpdateRoleAsync(systemIdentifier, roleId, roleName, inheritRoleId);
    public Task DeleteRoleAsync(string systemIdentifier, int roleId) => _client.DeleteRoleAsync(systemIdentifier, roleId);
    public Task<bool> GetUserInLeasingAgentListAsync(string systemIdentifier, int siteId) => _client.GetUserInLeasingAgentListAsync(systemIdentifier, siteId);
    public Task<bool> AuthenticateAsync(string username, string password, string additionalInfo) => _client.authenticateAsync(username, password, additionalInfo);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class NameValuePair : object, System.ComponentModel.INotifyPropertyChanged
{

    private string nameField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
            this.RaisePropertyChanged("Name");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
            this.RaisePropertyChanged("Value");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string rightIDField;

    private string rightDescriptionField;

    private string centerNameField;

    private bool assignedField;

    private int rolesAssignedField;

    private string usageDescriptionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string RightID
    {
        get
        {
            return this.rightIDField;
        }
        set
        {
            this.rightIDField = value;
            this.RaisePropertyChanged("RightID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string RightDescription
    {
        get
        {
            return this.rightDescriptionField;
        }
        set
        {
            this.rightDescriptionField = value;
            this.RaisePropertyChanged("RightDescription");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string CenterName
    {
        get
        {
            return this.centerNameField;
        }
        set
        {
            this.centerNameField = value;
            this.RaisePropertyChanged("CenterName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool Assigned
    {
        get
        {
            return this.assignedField;
        }
        set
        {
            this.assignedField = value;
            this.RaisePropertyChanged("Assigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public int RolesAssigned
    {
        get
        {
            return this.rolesAssignedField;
        }
        set
        {
            this.rolesAssignedField = value;
            this.RaisePropertyChanged("RolesAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string UsageDescription
    {
        get
        {
            return this.usageDescriptionField;
        }
        set
        {
            this.usageDescriptionField = value;
            this.RaisePropertyChanged("UsageDescription");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private RightType[] rightField;

    private int totalRightsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public RightType[] Right
    {
        get
        {
            return this.rightField;
        }
        set
        {
            this.rightField = value;
            this.RaisePropertyChanged("Right");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalRights
    {
        get
        {
            return this.totalRightsField;
        }
        set
        {
            this.totalRightsField = value;
            this.RaisePropertyChanged("TotalRights");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RightCenter : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private string[] rightCentersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public string[] RightCenters
    {
        get
        {
            return this.rightCentersField;
        }
        set
        {
            this.rightCentersField = value;
            this.RaisePropertyChanged("RightCenters");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RoleType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string roleIDField;

    private string roleNameField;

    private string rightsAssignedField;

    private bool isInternalField;

    private string roletypeField;

    private bool isAssignedField;

    private string inheritedRoleNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string RoleID
    {
        get
        {
            return this.roleIDField;
        }
        set
        {
            this.roleIDField = value;
            this.RaisePropertyChanged("RoleID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string RoleName
    {
        get
        {
            return this.roleNameField;
        }
        set
        {
            this.roleNameField = value;
            this.RaisePropertyChanged("RoleName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string RightsAssigned
    {
        get
        {
            return this.rightsAssignedField;
        }
        set
        {
            this.rightsAssignedField = value;
            this.RaisePropertyChanged("RightsAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool IsInternal
    {
        get
        {
            return this.isInternalField;
        }
        set
        {
            this.isInternalField = value;
            this.RaisePropertyChanged("IsInternal");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string Roletype
    {
        get
        {
            return this.roletypeField;
        }
        set
        {
            this.roletypeField = value;
            this.RaisePropertyChanged("Roletype");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public bool IsAssigned
    {
        get
        {
            return this.isAssignedField;
        }
        set
        {
            this.isAssignedField = value;
            this.RaisePropertyChanged("IsAssigned");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string InheritedRoleName
    {
        get
        {
            return this.inheritedRoleNameField;
        }
        set
        {
            this.inheritedRoleNameField = value;
            this.RaisePropertyChanged("InheritedRoleName");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class RoleList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private RoleType[] roleField;

    private int totalRolesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public RoleType[] Role
    {
        get
        {
            return this.roleField;
        }
        set
        {
            this.roleField = value;
            this.RaisePropertyChanged("Role");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalRoles
    {
        get
        {
            return this.totalRolesField;
        }
        set
        {
            this.totalRolesField = value;
            this.RaisePropertyChanged("TotalRoles");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserType : object, System.ComponentModel.INotifyPropertyChanged
{

    private int userIdField;

    private string userLoginField;

    private string userNameField;

    private bool assignedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int UserId
    {
        get
        {
            return this.userIdField;
        }
        set
        {
            this.userIdField = value;
            this.RaisePropertyChanged("UserId");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string UserLogin
    {
        get
        {
            return this.userLoginField;
        }
        set
        {
            this.userLoginField = value;
            this.RaisePropertyChanged("UserLogin");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string UserName
    {
        get
        {
            return this.userNameField;
        }
        set
        {
            this.userNameField = value;
            this.RaisePropertyChanged("UserName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public bool Assigned
    {
        get
        {
            return this.assignedField;
        }
        set
        {
            this.assignedField = value;
            this.RaisePropertyChanged("Assigned");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private UserType[] userField;

    private int totalUsersField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public UserType[] User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
            this.RaisePropertyChanged("User");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalUsers
    {
        get
        {
            return this.totalUsersField;
        }
        set
        {
            this.totalUsersField = value;
            this.RaisePropertyChanged("TotalUsers");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PropertyType : object, System.ComponentModel.INotifyPropertyChanged
{

    private string propertyIDField;

    private string propertyNameField;

    private string siteAddressField;

    private string siteCityNameField;

    private string siteStateField;

    private string siteZipField;

    private string sitePhoneField;

    private bool isAssignedToUserField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string PropertyID
    {
        get
        {
            return this.propertyIDField;
        }
        set
        {
            this.propertyIDField = value;
            this.RaisePropertyChanged("PropertyID");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string PropertyName
    {
        get
        {
            return this.propertyNameField;
        }
        set
        {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string SiteAddress
    {
        get
        {
            return this.siteAddressField;
        }
        set
        {
            this.siteAddressField = value;
            this.RaisePropertyChanged("SiteAddress");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string SiteCityName
    {
        get
        {
            return this.siteCityNameField;
        }
        set
        {
            this.siteCityNameField = value;
            this.RaisePropertyChanged("SiteCityName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SiteState
    {
        get
        {
            return this.siteStateField;
        }
        set
        {
            this.siteStateField = value;
            this.RaisePropertyChanged("SiteState");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
    public string SiteZip
    {
        get
        {
            return this.siteZipField;
        }
        set
        {
            this.siteZipField = value;
            this.RaisePropertyChanged("SiteZip");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
    public string SitePhone
    {
        get
        {
            return this.sitePhoneField;
        }
        set
        {
            this.sitePhoneField = value;
            this.RaisePropertyChanged("SitePhone");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
    public bool IsAssignedToUser
    {
        get
        {
            return this.isAssignedToUserField;
        }
        set
        {
            this.isAssignedToUserField = value;
            this.RaisePropertyChanged("IsAssignedToUser");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PropertyList : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorField;

    private PropertyType[] propertyField;

    private int totalPropertiesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
            this.RaisePropertyChanged("Error");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 1)]
    public PropertyType[] Property
    {
        get
        {
            return this.propertyField;
        }
        set
        {
            this.propertyField = value;
            this.RaisePropertyChanged("Property");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int TotalProperties
    {
        get
        {
            return this.totalPropertiesField;
        }
        set
        {
            this.totalPropertiesField = value;
            this.RaisePropertyChanged("TotalProperties");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class SortCondition : object, System.ComponentModel.INotifyPropertyChanged
{

    private string columnNameField;

    private string sortDirectionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ColumnName
    {
        get
        {
            return this.columnNameField;
        }
        set
        {
            this.columnNameField = value;
            this.RaisePropertyChanged("ColumnName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string SortDirection
    {
        get
        {
            return this.sortDirectionField;
        }
        set
        {
            this.sortDirectionField = value;
            this.RaisePropertyChanged("SortDirection");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class FilterCondition : object, System.ComponentModel.INotifyPropertyChanged
{

    private string propertyNameField;

    private string searchValueField;

    private string operatorField;

    private string querySuffixField;

    private string searchTypeField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string PropertyName
    {
        get
        {
            return this.propertyNameField;
        }
        set
        {
            this.propertyNameField = value;
            this.RaisePropertyChanged("PropertyName");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string SearchValue
    {
        get
        {
            return this.searchValueField;
        }
        set
        {
            this.searchValueField = value;
            this.RaisePropertyChanged("SearchValue");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public string Operator
    {
        get
        {
            return this.operatorField;
        }
        set
        {
            this.operatorField = value;
            this.RaisePropertyChanged("Operator");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public string QuerySuffix
    {
        get
        {
            return this.querySuffixField;
        }
        set
        {
            this.querySuffixField = value;
            this.RaisePropertyChanged("QuerySuffix");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
    public string SearchType
    {
        get
        {
            return this.searchTypeField;
        }
        set
        {
            this.searchTypeField = value;
            this.RaisePropertyChanged("SearchType");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class FilterSortParameters : object, System.ComponentModel.INotifyPropertyChanged
{

    private int startPositionField;

    private int pageLengthField;

    private FilterCondition[] filterConditionListField;

    private SortCondition sortConditionField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public int StartPosition
    {
        get
        {
            return this.startPositionField;
        }
        set
        {
            this.startPositionField = value;
            this.RaisePropertyChanged("StartPosition");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public int PageLength
    {
        get
        {
            return this.pageLengthField;
        }
        set
        {
            this.pageLengthField = value;
            this.RaisePropertyChanged("PageLength");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
    public FilterCondition[] FilterConditionList
    {
        get
        {
            return this.filterConditionListField;
        }
        set
        {
            this.filterConditionListField = value;
            this.RaisePropertyChanged("FilterConditionList");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
    public SortCondition SortCondition
    {
        get
        {
            return this.sortConditionField;
        }
        set
        {
            this.sortConditionField = value;
            this.RaisePropertyChanged("SortCondition");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class AssignStatus : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorMessageField;

    private bool resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
            this.RaisePropertyChanged("ErrorMessage");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
            this.RaisePropertyChanged("Result");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class PMCInfo : object, System.ComponentModel.INotifyPropertyChanged
{

    private string dBMachineField;

    private string pMCURLField;

    private int idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string DBMachine
    {
        get
        {
            return this.dBMachineField;
        }
        set
        {
            this.dBMachineField = value;
            this.RaisePropertyChanged("DBMachine");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public string PMCURL
    {
        get
        {
            return this.pMCURLField;
        }
        set
        {
            this.pMCURLField = value;
            this.RaisePropertyChanged("PMCURL");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
            this.RaisePropertyChanged("ID");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://realpage.com/webservices")]
public partial class UserExists : object, System.ComponentModel.INotifyPropertyChanged
{

    private string errorMessageField;

    private bool resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
    public string ErrorMessage
    {
        get
        {
            return this.errorMessageField;
        }
        set
        {
            this.errorMessageField = value;
            this.RaisePropertyChanged("ErrorMessage");
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
    public bool Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
            this.RaisePropertyChanged("Result");
        }
    }

    public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

    protected void RaisePropertyChanged(string propertyName)
    {
        System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
        if ((propertyChanged != null))
        {
            propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateSuperuser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateSuperuserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public CreateSuperuserRequest()
    {
    }

    public CreateSuperuserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateSuperuserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateSuperuserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public CreateSuperuserResponse()
    {
    }

    public CreateSuperuserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public CreateUserRequest()
    {
    }

    public CreateUserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "CreateUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class CreateUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public CreateUserResponse()
    {
    }

    public CreateUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateSuperuser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateSuperuserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public string SystemIdentifier;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 1)]
    public OneSite.NameValuePair[] User;

    public UpdateSuperuserRequest()
    {
    }

    public UpdateSuperuserRequest(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        this.SystemIdentifier = SystemIdentifier;
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateSuperuserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateSuperuserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public UpdateSuperuserResponse()
    {
    }

    public UpdateSuperuserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public string SystemIdentifier;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 1)]
    public OneSite.NameValuePair[] User;

    public UpdateUserRequest()
    {
    }

    public UpdateUserRequest(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        this.SystemIdentifier = SystemIdentifier;
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "UpdateUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class UpdateUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public UpdateUserResponse()
    {
    }

    public UpdateUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetUser", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class GetUserRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    public OneSite.NameValuePair[] User;

    public GetUserRequest()
    {
    }

    public GetUserRequest(OneSite.NameValuePair[] User)
    {
        this.User = User;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "GetUserResponse", WrapperNamespace = "http://realpage.com/webservices", IsWrapped = true)]
public partial class GetUserResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://realpage.com/webservices", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute("UserInfo")]
    public OneSite.NameValuePair[] UserInfo;

    public GetUserResponse()
    {
    }

    public GetUserResponse(OneSite.NameValuePair[] UserInfo)
    {
        this.UserInfo = UserInfo;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public interface ProductServicePortBindingChannel : OneSite.ProductServicePortBinding, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
public partial class ProductServicePortBindingClient : System.ServiceModel.ClientBase<OneSite.ProductServicePortBinding>, OneSite.ProductServicePortBinding
{

    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

    public ProductServicePortBindingClient(EndpointConfiguration endpointConfiguration) :
            base(ProductServicePortBindingClient.GetBindingForEndpoint(endpointConfiguration), ProductServicePortBindingClient.GetEndpointAddress(endpointConfiguration))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductServicePortBindingClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
            base(ProductServicePortBindingClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductServicePortBindingClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
            base(ProductServicePortBindingClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
    {
        this.Endpoint.Name = endpointConfiguration.ToString();
        ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
    }

    public ProductServicePortBindingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public System.Threading.Tasks.Task<bool> ValidateUserAsync(OneSite.NameValuePair[] User, string Password)
    {
        return base.Channel.ValidateUserAsync(User, Password);
    }

    public System.Threading.Tasks.Task<OneSite.UserExists> CheckIfUserIDIsUsedAsync(OneSite.NameValuePair[] uiArgs)
    {
        return base.Channel.CheckIfUserIDIsUsedAsync(uiArgs);
    }

    public System.Threading.Tasks.Task<OneSite.PMCInfo> GetPMCUrlAsync(int PMCID)
    {
        return base.Channel.GetPMCUrlAsync(PMCID);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.CreateSuperuserResponse> OneSite.ProductServicePortBinding.CreateSuperuserAsync(OneSite.CreateSuperuserRequest request)
    {
        return base.Channel.CreateSuperuserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.CreateSuperuserResponse> CreateSuperuserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.CreateSuperuserRequest inValue = new OneSite.CreateSuperuserRequest();
        inValue.User = User;
        return ((OneSite.ProductServicePortBinding)(this)).CreateSuperuserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.CreateUserResponse> OneSite.ProductServicePortBinding.CreateUserAsync(OneSite.CreateUserRequest request)
    {
        return base.Channel.CreateUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.CreateUserResponse> CreateUserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.CreateUserRequest inValue = new OneSite.CreateUserRequest();
        inValue.User = User;
        return ((OneSite.ProductServicePortBinding)(this)).CreateUserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.UpdateSuperuserResponse> OneSite.ProductServicePortBinding.UpdateSuperuserAsync(OneSite.UpdateSuperuserRequest request)
    {
        return base.Channel.UpdateSuperuserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.UpdateSuperuserResponse> UpdateSuperuserAsync(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateSuperuserRequest inValue = new OneSite.UpdateSuperuserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        return ((OneSite.ProductServicePortBinding)(this)).UpdateSuperuserAsync(inValue);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.UpdateUserResponse> OneSite.ProductServicePortBinding.UpdateUserAsync(OneSite.UpdateUserRequest request)
    {
        return base.Channel.UpdateUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.UpdateUserResponse> UpdateUserAsync(string SystemIdentifier, OneSite.NameValuePair[] User)
    {
        OneSite.UpdateUserRequest inValue = new OneSite.UpdateUserRequest();
        inValue.SystemIdentifier = SystemIdentifier;
        inValue.User = User;
        return ((OneSite.ProductServicePortBinding)(this)).UpdateUserAsync(inValue);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> AssignPropertiesToUserAsync(string SystemIdentifier, string SelectedPropertyIds)
    {
        return base.Channel.AssignPropertiesToUserAsync(SystemIdentifier, SelectedPropertyIds);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> RemovePropertiesFromUserAsync(string SystemIdentifier, string PropertyIdsToRemove)
    {
        return base.Channel.RemovePropertiesFromUserAsync(SystemIdentifier, PropertyIdsToRemove);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> AssignRolesToUserAsync(string SystemIdentifier, string SelectedRoleIds)
    {
        return base.Channel.AssignRolesToUserAsync(SystemIdentifier, SelectedRoleIds);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> RemoveRolesFromUserAsync(string SystemIdentifier, string RoleIdsToRemove)
    {
        return base.Channel.RemoveRolesFromUserAsync(SystemIdentifier, RoleIdsToRemove);
    }

    public System.Threading.Tasks.Task EnableUserAsync(string SystemIdentifier)
    {
        return base.Channel.EnableUserAsync(SystemIdentifier);
    }

    public System.Threading.Tasks.Task ResetVerificationCodeAsync(string SystemIdentifier)
    {
        return base.Channel.ResetVerificationCodeAsync(SystemIdentifier);
    }

    public System.Threading.Tasks.Task DisableUserAsync(string SystemIdentifier)
    {
        return base.Channel.DisableUserAsync(SystemIdentifier);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetAllPropertiesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllPropertiesAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetDefaultPropertiesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultPropertiesAsync(uiArgs, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.PropertyList> GetUserPropertiesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserPropertiesAsync(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.UserList> GetUsersForPropertyAsync(string SystemIdentifier, int PropertyID, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForPropertyAsync(SystemIdentifier, PropertyID, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetAllRolesAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetAllRolesAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetDefaultRolesAsync(OneSite.NameValuePair[] uiArgs, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetDefaultRolesAsync(uiArgs, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetUserRolesAsync(string SystemIdentifier, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUserRolesAsync(SystemIdentifier, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.UserList> GetUsersForRoleAsync(string SystemIdentifier, int RoleId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetUsersForRoleAsync(SystemIdentifier, RoleId, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task DeleteUserAsync(string SystemIdentifier, string DeleteUserSystemIdentifier)
    {
        return base.Channel.DeleteUserAsync(SystemIdentifier, DeleteUserSystemIdentifier);
    }

    public System.Threading.Tasks.Task ClaimUserAsync(string SystemIdentifier, bool IsLinked)
    {
        return base.Channel.ClaimUserAsync(SystemIdentifier, IsLinked);
    }

    public System.Threading.Tasks.Task ClaimUserULAsync(string SystemIdentifier, bool IsULLinked)
    {
        return base.Channel.ClaimUserULAsync(SystemIdentifier, IsULLinked);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<OneSite.GetUserResponse> OneSite.ProductServicePortBinding.GetUserAsync(OneSite.GetUserRequest request)
    {
        return base.Channel.GetUserAsync(request);
    }

    public System.Threading.Tasks.Task<OneSite.GetUserResponse> GetUserAsync(OneSite.NameValuePair[] User)
    {
        OneSite.GetUserRequest inValue = new OneSite.GetUserRequest();
        inValue.User = User;
        return ((OneSite.ProductServicePortBinding)(this)).GetUserAsync(inValue);
    }

    public System.Threading.Tasks.Task<OneSite.RightCenter> GetRightsCentersListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier)
    {
        return base.Channel.GetRightsCentersListAsync(uiArgs, SystemIdentifier);
    }

    public System.Threading.Tasks.Task<OneSite.RightList> GetRightsListAsync(OneSite.NameValuePair[] uiArgs, string SystemIdentifier, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRightsListAsync(uiArgs, SystemIdentifier, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRightToRolesAsync(string SystemIdentifier, int RightId, string SelectedRoleIds, bool AssignRight)
    {
        return base.Channel.ModifyRightToRolesAsync(SystemIdentifier, RightId, SelectedRoleIds, AssignRight);
    }

    public System.Threading.Tasks.Task<OneSite.AssignStatus> ModifyRoleToRightsAsync(string SystemIdentifier, int RoleId, string RightIdsToAdd, string RightIdsToRemove)
    {
        return base.Channel.ModifyRoleToRightsAsync(SystemIdentifier, RoleId, RightIdsToAdd, RightIdsToRemove);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> GetRolesForRightAsync(OneSite.NameValuePair[] uiArgs, int RightId, bool AssignedOnly, OneSite.FilterSortParameters filterSortParameters)
    {
        return base.Channel.GetRolesForRightAsync(uiArgs, RightId, AssignedOnly, filterSortParameters);
    }

    public System.Threading.Tasks.Task<OneSite.RoleList> AddUpdateRoleAsync(string SystemIdentifier, string RoleId, string RoleName, string InheritRoleID)
    {
        return base.Channel.AddUpdateRoleAsync(SystemIdentifier, RoleId, RoleName, InheritRoleID);
    }

    public System.Threading.Tasks.Task DeleteRoleAsync(string SystemIdentifier, int RoleID)
    {
        return base.Channel.DeleteRoleAsync(SystemIdentifier, RoleID);
    }

    public System.Threading.Tasks.Task<bool> GetUserInLeasingAgentListAsync(string SystemIdentifier, int SiteID)
    {
        return base.Channel.GetUserInLeasingAgentListAsync(SystemIdentifier, SiteID);
    }

    public System.Threading.Tasks.Task<bool> authenticateAsync(string username, string password, string additionalInfo)
    {
        return base.Channel.authenticateAsync(username, password, additionalInfo);
    }

    public virtual System.Threading.Tasks.Task OpenAsync()
    {
        return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
    }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

    private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding))
        {
            System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
            result.MaxBufferSize = int.MaxValue;
            result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
            result.MaxReceivedMessageSize = int.MaxValue;
            result.AllowCookies = true;
            result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
            return result;
        }
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding1))
        {
            System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
            System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
            textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
            result.Elements.Add(textBindingElement);
            System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
            httpsBindingElement.AllowCookies = true;
            httpsBindingElement.MaxBufferSize = int.MaxValue;
            httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
            result.Elements.Add(httpsBindingElement);
            return result;
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
    {
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding))
        {
            return new System.ServiceModel.EndpointAddress("https://sat.realpage.com/logonsvc/productservice.asmx");
        }
        if ((endpointConfiguration == EndpointConfiguration.ProductServicePortBinding1))
        {
            return new System.ServiceModel.EndpointAddress("https://sat.realpage.com/logonsvc/productservice.asmx");
        }
        throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
    }

    public enum EndpointConfiguration
    {

        ProductServicePortBinding,

        ProductServicePortBinding1,
    }
}